# Generated by scripts/build_submission.py. Edit controller/ instead.
from dataclasses import dataclass
import math

import cv2
import numpy as np


# ---- common.py ----

"""公共数据结构和基础工具。

功能概述：定义模块间共享的数据契约和数值限幅函数。
输入输出：输入各模块产生的原始数值，输出带字段约束的 dataclass 或裁剪后的数值。
处理流程：先声明感知、估计、模式、转向、速度五类结构，再提供统一的 `clamp()`。
"""




@dataclass
class PerceptionObs:
    """视觉感知结果。

    功能：承载扫描线中心点、左右边界点、道路宽度和感知置信度。
    参数：各字段由 `perception.extract_observation()` 生成。
    返回：dataclass 实例。
    逻辑：字段名作为模块契约，后续估计模块只读取这些字段。
    """

    center_points: np.ndarray
    left_edge_points: np.ndarray
    right_edge_points: np.ndarray
    road_width_est: float
    confidence: float
    debug_flags: int = 0


@dataclass
class TrackState:
    """赛道几何状态。

    功能：保存控制所需的偏移、方向、曲率、前瞻误差和丢线状态。
    参数：字段由 `estimator.estimate_track()` 估计。
    返回：dataclass 实例。
    逻辑：统一使用左负右正的误差符号，便于转向和速度策略复用。
    """

    lateral_error: float
    heading_error: float
    curvature: float
    lookahead_error: float
    confidence: float
    lost: bool


@dataclass
class ControlMode:
    """驾驶模式。

    功能：表达当前处于 normal、caution、lost 或 recovery 模式。
    参数：`name` 是模式名，`risk` 是 0 到 1 的风险值。
    返回：dataclass 实例。
    逻辑：策略模块根据几何状态判断风险，其他模块只消费结果。
    """

    name: str
    risk: float


@dataclass
class SteeringCmd:
    """转向命令。

    功能：保存转向值和转向决策置信度。
    参数：`value` 是方向盘比例，`confidence` 是 0 到 1 的可信度。
    返回：dataclass 实例。
    逻辑：转向模块负责限幅，顶层入口仍会做最终兜底限幅。
    """

    value: float
    confidence: float


@dataclass
class SpeedCmd:
    """速度命令。

    功能：保存速度值和速度决策置信度。
    参数：`value` 是速度比例，`confidence` 是 0 到 1 的可信度。
    返回：dataclass 实例。
    逻辑：策略模块负责降速规则，顶层入口负责最终限幅。
    """

    value: float
    confidence: float


def clamp(x: float, lo: float, hi: float) -> float:
    """把数值限制在指定区间。

    功能：防止控制量、风险值和置信度越界。
    参数：`x` 是待裁剪数值，`lo` 和 `hi` 是上下界。
    返回：落在 `[lo, hi]` 内的浮点数。
    逻辑：先转成 float，再依次应用上下界。
    """

    return max(lo, min(hi, float(x)))



# ---- params.py ----

"""策略参数配置。

功能概述：集中保存视觉、估计、转向和速度策略参数。
输入输出：输入 profile 名称，输出对应参数字典。
处理流程：先定义通用感知和估计参数，再定义 fastest/safe 两套控制 profile。
"""

VISION_PROFILE = {
    "roi_top_ratio": 0.42,
    "scan_top_ratio": 0.50,
    "scan_bottom_ratio": 0.92,
    "scan_count": 12,
    "min_pixels_per_scan": 8,
    "min_road_width": 18.0,
}

ESTIMATOR_PROFILE = {
    "lost_confidence": 0.08,
    "smooth_alpha": 0.28,
}

FAST_PROFILE = {
    "base_speed": 0.86,
    "max_speed": 1.0,
    "min_speed": 0.20,
    "lost_speed": 0.18,
    "recovery_speed": 0.26,
    "caution_speed": 0.58,
    "curve_slowdown": 0.42,
    "offset_slowdown": 0.20,
    "steering_slowdown": 0.08,
    "risk_slowdown": 0.24,
    "lateral_gain": 1.05,
    "heading_gain": 0.34,
    "lookahead_gain": 0.28,
    "curvature_gain": 0.38,
    "steering_deadzone": 0.018,
    "steering_smooth": 0.30,
    "caution_steering_smooth": 0.42,
    "max_steering_delta": 0.22,
    "nominal_dt": 0.032,
    "recovery_steering_scale": 0.72,
    "caution_risk": 0.58,
    "lost_risk": 0.92,
    "recovery_confidence": 0.28,
    "start_caution_seconds": 0.8,
}

SAFE_PROFILE = {
    "base_speed": 0.66,
    "max_speed": 0.82,
    "min_speed": 0.16,
    "lost_speed": 0.12,
    "recovery_speed": 0.20,
    "caution_speed": 0.44,
    "curve_slowdown": 0.54,
    "offset_slowdown": 0.30,
    "steering_slowdown": 0.12,
    "risk_slowdown": 0.34,
    "lateral_gain": 0.98,
    "heading_gain": 0.30,
    "lookahead_gain": 0.24,
    "curvature_gain": 0.42,
    "steering_deadzone": 0.022,
    "steering_smooth": 0.40,
    "caution_steering_smooth": 0.56,
    "max_steering_delta": 0.16,
    "nominal_dt": 0.032,
    "recovery_steering_scale": 0.62,
    "caution_risk": 0.46,
    "lost_risk": 0.96,
    "recovery_confidence": 0.36,
    "start_caution_seconds": 1.2,
}


def get_profile(name: str) -> dict:
    """按名称读取控制 profile。

    功能：为顶层控制器提供 fastest 或 safe 参数。
    参数：`name` 只能是 `fastest` 或 `safe`。
    返回：对应参数字典的浅拷贝。
    逻辑：浅拷贝可避免调用方误改全局参数；未知名称直接回退到 safe。
    """

    if name == "fastest":
        return dict(FAST_PROFILE)
    if name == "safe":
        return dict(SAFE_PROFILE)
    return dict(SAFE_PROFILE)



# ---- perception.py ----

"""视觉感知模块。

功能概述：从左右摄像头图像中提取赛道边界、中心点和感知置信度。
输入输出：输入 BGR 图像，输出 `PerceptionObs`。
处理流程：裁剪中下部 ROI，生成轻量二值掩膜，按扫描线提取左右边界并估计中心点。
"""




def _empty_obs() -> PerceptionObs:
    points = np.empty((0, 2), dtype=np.float32)
    return PerceptionObs(points, points, points, 0.0, 0.0, debug_flags=1)


def _valid_image(image) -> bool:
    return image is not None and hasattr(image, "shape") and len(image.shape) == 3 and image.shape[2] == 3


def _make_mask(image: np.ndarray) -> np.ndarray:
    """生成赛道线索掩膜。

    功能：把亮色区域、灰度高对比区域和边缘线索合并成二值图。
    参数：`image` 是单个摄像头 BGR 图像。
    返回：uint8 掩膜，非零像素表示可能的赛道边界或可行驶区域。
    逻辑：多线索融合比单一颜色阈值更抗赛道材质变化。
    """

    height = image.shape[0]
    top = int(height * VISION_PROFILE["roi_top_ratio"])
    roi = image[top:, :, :]

    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)

    bright = cv2.inRange(hsv, np.array([0, 0, 125]), np.array([180, 100, 255]))
    _, adaptive = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    edges = cv2.Canny(cv2.GaussianBlur(gray, (5, 5), 0), 45, 120)

    mask = cv2.bitwise_or(cv2.bitwise_or(bright, adaptive), edges)
    kernel = np.ones((5, 5), dtype=np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=1)

    padded = np.zeros(image.shape[:2], dtype=np.uint8)
    padded[top:, :] = mask
    return padded


def _scan_image(image: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, float]:
    """按扫描线提取单张图中的边界和中心点。

    功能：在若干水平扫描线上寻找左右边界，并估计赛道中心。
    参数：`image` 是单个摄像头图像。
    返回：中心点、左边界点、右边界点、道路宽度、置信度。
    逻辑：从近处到远处扫描，点数和道路宽度稳定性共同决定置信度。
    """

    mask = _make_mask(image)
    height, width = mask.shape
    rows = np.linspace(
        int(height * VISION_PROFILE["scan_bottom_ratio"]),
        int(height * VISION_PROFILE["scan_top_ratio"]),
        int(VISION_PROFILE["scan_count"]),
        dtype=np.int32,
    )

    centers = []
    left_edges = []
    right_edges = []
    widths = []

    for y in rows:
        xs = np.flatnonzero(mask[y])
        if xs.size < VISION_PROFILE["min_pixels_per_scan"]:
            continue
        left = float(xs[0])
        right = float(xs[-1])
        road_width = right - left
        if road_width < VISION_PROFILE["min_road_width"]:
            continue
        center = (left + right) * 0.5
        centers.append((center, float(y)))
        left_edges.append((left, float(y)))
        right_edges.append((right, float(y)))
        widths.append(road_width)

    if not centers:
        empty = np.empty((0, 2), dtype=np.float32)
        return empty, empty, empty, 0.0, 0.0

    center_arr = np.array(centers, dtype=np.float32)
    left_arr = np.array(left_edges, dtype=np.float32)
    right_arr = np.array(right_edges, dtype=np.float32)
    width_est = float(np.median(np.array(widths, dtype=np.float32)))
    confidence = clamp(len(centers) / float(VISION_PROFILE["scan_count"]), 0.0, 1.0)
    return center_arr, left_arr, right_arr, width_est, confidence


def extract_observation(left_img, right_img) -> PerceptionObs:
    """提取左右摄像头的赛道观测。

    功能：输出中心点、边界点、道路宽度估计和感知置信度。
    参数：`left_img` 与 `right_img` 是平台传入的 BGR 图像。
    返回：`PerceptionObs`。
    逻辑：分别扫描有效图像，合并结果；全部失败时返回低置信度空观测。
    """

    chunks = []
    widths = []
    confidences = []

    for image in (left_img, right_img):
        if not _valid_image(image):
            continue
        centers, left_edges, right_edges, width_est, confidence = _scan_image(image)
        chunks.append((centers, left_edges, right_edges))
        if width_est > 0:
            widths.append(width_est)
        confidences.append(confidence)

    if not chunks:
        return _empty_obs()

    center_points = np.concatenate([item[0] for item in chunks], axis=0)
    left_edge_points = np.concatenate([item[1] for item in chunks], axis=0)
    right_edge_points = np.concatenate([item[2] for item in chunks], axis=0)

    if center_points.size == 0:
        return _empty_obs()

    confidence = clamp(float(np.mean(confidences)), 0.0, 1.0)
    road_width_est = float(np.median(np.array(widths, dtype=np.float32))) if widths else 0.0
    return PerceptionObs(center_points, left_edge_points, right_edge_points, road_width_est, confidence)



# ---- estimator.py ----

"""赛道几何估计模块。

功能概述：把感知点转换成横向偏移、方向误差、曲率和前瞻误差。
输入输出：输入 `PerceptionObs` 和时间戳，输出 `TrackState`。
处理流程：按近远扫描点分组，计算近处偏移、远处偏移和中心线斜率，再做轻量平滑。
"""



_LAST_TRACK = TrackState(0.0, 0.0, 0.0, 0.0, 0.0, True)


def _image_center(points: np.ndarray) -> float:
    if points.size == 0:
        return 320.0
    max_x = float(np.max(points[:, 0]))
    min_x = float(np.min(points[:, 0]))
    width_guess = max(640.0, max_x - min_x)
    return width_guess * 0.5


def _weighted_x(points: np.ndarray, near: bool) -> float:
    y = points[:, 1]
    if near:
        weights = 0.35 + y / max(float(np.max(y)), 1.0)
    else:
        weights = 1.35 - y / max(float(np.max(y)), 1.0)
    return float(np.average(points[:, 0], weights=weights))


def _smooth_value(previous: float, current: float, alpha: float) -> float:
    return previous * alpha + current * (1.0 - alpha)


def reset_estimator_state() -> None:
    """重置估计器跨帧状态。

    功能：让测试或新一轮仿真从干净状态开始。
    参数：无。
    返回：无。
    逻辑：把上一帧状态写回低置信度丢线状态。
    """

    global _LAST_TRACK
    _LAST_TRACK = TrackState(0.0, 0.0, 0.0, 0.0, 0.0, True)


def estimate_track(obs: PerceptionObs, timestamp: float) -> TrackState:
    """估计赛道几何状态。

    功能：根据中心点估计控制模块需要的几何量。
    参数：`obs` 是感知结果，`timestamp` 是平台时间戳。
    返回：`TrackState`。
    逻辑：点数不足时进入丢线状态；点数足够时计算近处、远处和整体趋势并平滑输出。
    """

    del timestamp
    global _LAST_TRACK

    points = obs.center_points
    if points.size == 0 or obs.confidence < ESTIMATOR_PROFILE["lost_confidence"]:
        recovered = TrackState(
            _LAST_TRACK.lateral_error * 0.85,
            _LAST_TRACK.heading_error * 0.80,
            _LAST_TRACK.curvature * 0.80,
            _LAST_TRACK.lookahead_error * 0.85,
            max(obs.confidence, 0.0),
            True,
        )
        _LAST_TRACK = recovered
        return recovered

    points = points[np.argsort(points[:, 1])]
    center_x = _image_center(points)
    scale = max(center_x, 1.0)

    near_x = _weighted_x(points, near=True)
    far_x = _weighted_x(points, near=False)
    lateral_error = clamp((near_x - center_x) / scale, -1.0, 1.0)
    lookahead_error = clamp((far_x - center_x) / scale, -1.0, 1.0)

    if len(points) >= 2:
        fit = np.polyfit(points[:, 1], points[:, 0], deg=1)
        heading_error = clamp(float(fit[0]) * 1.6, -1.0, 1.0)
    else:
        heading_error = 0.0

    curvature = clamp(lookahead_error - lateral_error, -1.0, 1.0)
    alpha = ESTIMATOR_PROFILE["smooth_alpha"]
    track = TrackState(
        _smooth_value(_LAST_TRACK.lateral_error, lateral_error, alpha),
        _smooth_value(_LAST_TRACK.heading_error, heading_error, alpha),
        _smooth_value(_LAST_TRACK.curvature, curvature, alpha),
        _smooth_value(_LAST_TRACK.lookahead_error, lookahead_error, alpha),
        clamp(obs.confidence, 0.0, 1.0),
        False,
    )
    _LAST_TRACK = track
    return track



# ---- strategy.py ----

"""速度策略和模式切换模块。

功能概述：根据赛道状态、转向命令和 profile 选择驾驶模式并计算速度。
输入输出：输入 `TrackState`、`SteeringCmd` 和参数字典，输出 `ControlMode` 或 `SpeedCmd`。
处理流程：先按丢线、置信度和风险切模式，再按风险项削减基础速度。
"""




def _risk_from_track(track: TrackState) -> float:
    curve_risk = abs(track.curvature) * 0.45
    offset_risk = abs(track.lateral_error) * 0.35
    heading_risk = abs(track.heading_error) * 0.20
    confidence_risk = 1.0 - track.confidence
    return clamp(curve_risk + offset_risk + heading_risk + confidence_risk * 0.45, 0.0, 1.0)


def select_mode(track: TrackState, timestamp: float, profile: dict) -> ControlMode:
    """选择驾驶模式。

    功能：把连续风险值转换为 normal、caution、lost 或 recovery。
    参数：`track` 是几何状态，`timestamp` 是平台时间，`profile` 是策略参数。
    返回：`ControlMode`。
    逻辑：丢线优先，其次看置信度和综合风险；启动阶段可更保守。
    """

    risk = _risk_from_track(track)
    if track.lost:
        return ControlMode("lost", max(risk, profile["lost_risk"]))
    if track.confidence < profile["recovery_confidence"]:
        return ControlMode("recovery", max(risk, 0.72))
    if timestamp < profile["start_caution_seconds"] or risk > profile["caution_risk"]:
        return ControlMode("caution", risk)
    return ControlMode("normal", risk)


def compute_speed(
    track: TrackState,
    steering: SteeringCmd,
    mode: ControlMode,
    timestamp: float,
    profile: dict,
) -> SpeedCmd:
    """计算速度命令。

    功能：在稳定直道提速，在急弯、低置信度、丢线和大转向时降速。
    参数：`track` 是赛道状态，`steering` 是转向命令，`mode` 是驾驶模式，`profile` 是策略参数。
    返回：`SpeedCmd`。
    逻辑：从基础速度出发，按曲率、偏移、转向和模式风险逐项扣减。
    """

    del timestamp

    if mode.name == "lost":
        return SpeedCmd(profile["lost_speed"], track.confidence)
    if mode.name == "recovery":
        return SpeedCmd(profile["recovery_speed"], track.confidence)

    curve_penalty = abs(track.curvature) * profile["curve_slowdown"]
    offset_penalty = abs(track.lateral_error) * profile["offset_slowdown"]
    steering_penalty = math.sqrt(abs(steering.value)) * profile["steering_slowdown"]
    risk_penalty = mode.risk * profile["risk_slowdown"]

    speed = profile["base_speed"] - curve_penalty - offset_penalty - steering_penalty - risk_penalty
    if mode.name == "caution":
        speed = min(speed, profile["caution_speed"])

    value = clamp(speed, profile["min_speed"], profile["max_speed"])
    confidence = clamp(min(track.confidence, steering.confidence), 0.0, 1.0)
    return SpeedCmd(value, confidence)



# ---- steering.py ----

"""转向控制模块。

功能概述：根据赛道几何状态和驾驶模式计算方向盘比例。
输入输出：输入 `TrackState`、`ControlMode`、时间戳和 profile，输出 `SteeringCmd`。
处理流程：组合横向偏移、朝向误差、前瞻误差和曲率，再做死区、平滑和变化率限制。
"""


_LAST_STEERING = 0.0
_LAST_TIMESTAMP = None


def reset_steering_state() -> None:
    """重置转向跨帧状态。

    功能：清空上一帧转向和时间戳。
    参数：无。
    返回：无。
    逻辑：测试或新仿真开始前调用，避免继承旧平滑状态。
    """

    global _LAST_STEERING, _LAST_TIMESTAMP
    _LAST_STEERING = 0.0
    _LAST_TIMESTAMP = None


def compute_steering(
    track: TrackState,
    mode: ControlMode,
    timestamp: float,
    profile: dict,
) -> SteeringCmd:
    """计算转向命令。

    功能：输出范围稳定的方向盘比例。
    参数：`track` 是赛道状态，`mode` 是驾驶模式，`timestamp` 是平台时间，`profile` 是策略参数。
    返回：`SteeringCmd`。
    逻辑：正常模式响应更快，风险模式加大平滑并限制单帧变化。
    """

    global _LAST_STEERING, _LAST_TIMESTAMP

    raw = (
        track.lateral_error * profile["lateral_gain"]
        + track.heading_error * profile["heading_gain"]
        + track.lookahead_error * profile["lookahead_gain"]
        + track.curvature * profile["curvature_gain"]
    )

    if abs(raw) < profile["steering_deadzone"]:
        raw = 0.0

    if mode.name in {"lost", "recovery"}:
        raw *= profile["recovery_steering_scale"]

    raw = clamp(raw, -1.0, 1.0)
    alpha = profile["caution_steering_smooth"] if mode.name != "normal" else profile["steering_smooth"]
    smoothed = _LAST_STEERING * alpha + raw * (1.0 - alpha)

    if _LAST_TIMESTAMP is None:
        max_delta = profile["max_steering_delta"]
    else:
        elapsed = max(float(timestamp) - float(_LAST_TIMESTAMP), 0.0)
        max_delta = profile["max_steering_delta"] * max(1.0, elapsed / profile["nominal_dt"])

    delta = clamp(smoothed - _LAST_STEERING, -max_delta, max_delta)
    value = clamp(_LAST_STEERING + delta, -1.0, 1.0)
    _LAST_STEERING = value
    _LAST_TIMESTAMP = timestamp

    confidence = clamp(track.confidence * (1.0 - mode.risk * 0.35), 0.0, 1.0)
    return SteeringCmd(value, confidence)



# ---- team_controller_local.py ----

"""本地控制器入口。

功能概述：按固定流水线串接感知、估计、模式、转向和速度模块。
输入输出：输入平台同形态的左右图像和时间戳，输出 `(steering, speed)`。
处理流程：读取 profile，提取观测，估计赛道，选择模式，计算转向和速度，最后限幅返回。
"""


PROFILE = "fastest"


def control(left_img, right_img, timestamp):
    """平台兼容的控制入口。

    功能：提供 `control(left_img, right_img, timestamp)` 接口。
    参数：`left_img`、`right_img` 是 BGR 图像，`timestamp` 是仿真时间。
    返回：`(steering, speed)`，两个值都在平台允许范围内。
    逻辑：仅负责模块接线和异常兜底，具体算法留在各职责模块中。
    """

    try:
        profile = get_profile(PROFILE)
        obs = extract_observation(left_img, right_img)
        track = estimate_track(obs, timestamp)
        mode = select_mode(track, timestamp, profile)
        steering_cmd = compute_steering(track, mode, timestamp, profile)
        speed_cmd = compute_speed(track, steering_cmd, mode, timestamp, profile)
        return clamp(steering_cmd.value, -1.0, 1.0), clamp(speed_cmd.value, 0.0, 1.0)
    except Exception:
        return 0.0, 0.0
