# Generated by scripts/build_submission.py. Edit controller/ instead.
from dataclasses import dataclass
import math

import cv2
import numpy as np


# ---- common.py ----

"""公共数据结构和基础工具。

功能概述：定义控制流水线共享的数据契约和数值限幅函数。
输入输出：输入各模块产生的原始数值，输出 dataclass 或平台可用的控制二元组。
处理流程：声明感知结果、赛道状态和控制命令，再提供统一的裁剪工具。
"""




@dataclass
class PerceptionObs:
    """视觉感知结果。

    功能：承载扫描线中心点、左右边界点、道路宽度和感知置信度。
    参数：各字段由 `perception.extract_observation()` 生成。
    返回：dataclass 实例。
    逻辑：字段名作为模块契约，后续估计模块只读取这些字段。
    """

    center_points: np.ndarray
    left_edge_points: np.ndarray
    right_edge_points: np.ndarray
    road_width_est: float
    confidence: float
    debug_flags: int = 0


@dataclass
class TrackState:
    """赛道几何状态。

    功能：保存控制所需的偏移、方向、曲率、前瞻误差和丢线状态。
    参数：字段由 `estimator.estimate_track()` 估计。
    返回：dataclass 实例。
    逻辑：统一使用左负右正的误差符号，便于转向和速度策略复用。
    """

    lateral_error: float
    heading_error: float
    curvature: float
    lookahead_error: float
    confidence: float
    lost: bool
    red_environment: bool = False


@dataclass
class ControlCmd:
    """控制命令。

    功能：保存平台需要的转向和速度比例。
    参数：`steering` 是方向盘比例，`speed` 是速度比例。
    返回：dataclass 实例。
    逻辑：`policy.decide_control()` 产生命令，入口层用 `clamp_cmd()` 做最终限幅。
    """

    steering: float
    speed: float


def clamp(value: float, low: float, high: float) -> float:
    """把数值限制在指定区间。

    功能：防止控制量、风险值和置信度越界。
    参数：`value` 是待裁剪数值，`low` 和 `high` 是上下界。
    返回：落在 `[low, high]` 内的浮点数。
    逻辑：先转成 float，再依次应用上下界。
    """

    return max(low, min(high, float(value)))


def clamp_cmd(cmd: ControlCmd) -> tuple[float, float]:
    """裁剪平台控制二元组。

    功能：把控制命令转换成平台要求的 `(steering, speed)`。
    参数：`cmd` 是策略层输出的控制命令。
    返回：转向位于 `[-1.0, 1.0]`、速度位于 `[0.0, 1.0]` 的二元组。
    逻辑：入口层统一调用，避免各模块重复写最终范围保护。
    """

    return clamp(cmd.steering, -1.0, 1.0), clamp(cmd.speed, 0.0, 1.0)



# ---- params.py ----

"""策略参数配置。

功能概述：集中保存视觉、估计和控制策略参数。
输入输出：输入任意 profile 名称，输出同一套控制参数。
处理流程：先定义通用感知和估计参数，再定义唯一的 CONTROL 控制参数。
"""

VISION_PROFILE = {
    "roi_top_ratio": 0.42,
    "scan_top_ratio": 0.50,
    "scan_bottom_ratio": 0.92,
    "scan_count": 12,
    "row_band": 2,
    "road_lab_threshold": 34.0,
    "road_gray_min": 35.0,
    "road_gray_max": 105.0,
    "road_sat_max": 80.0,
    "grass_hue_min": 35.0,
    "grass_hue_max": 95.0,
    "grass_sat_min": 60.0,
    "grass_value_min": 40.0,
    "barrier_hue_min": 92.0,
    "barrier_hue_max": 118.0,
    "barrier_sat_min": 60.0,
    "barrier_value_min": 80.0,
    "barrier_value_max": 210.0,
    "dark_mask_min_fill": 0.04,
    "texture_gray_std_scale": 35.0,
    "min_segment_width": 24.0,
    "max_segment_gap": 90.0,
    "fallback_min_segment_width": 96.0,
    "fallback_initial_center_max_offset": 0.22,
    "fallback_narrow_jump_max_ratio": 0.16,
    "early_max_segment_width_ratio": 0.995,
    "red_world_min_ratio": 0.05,
    "max_segment_width_ratio": 0.90,
    "wide_segment_localize_ratio": 0.58,
    "wide_segment_window_ratio": 0.34,
    "max_center_jump_ratio": 0.35,
    "min_valid_scans": 4,
    "min_camera_confidence": 0.12,
    "empty_mask_confidence_scale": 0.25,
    "saturated_mask_confidence_scale": 0.25,
    "fusion_max_offset_gap": 0.18,
    "fusion_confidence_margin": 0.18,
    "fusion_merge_gap": 0.12,
    "fusion_merge_min_confidence": 0.35,
}

OPPONENT_PROFILE = {
    "enable_opponent_avoidance": True,
    "near_obstacle_segment_gap": 28.0,
    "near_obstacle_min_timestamp": 0.0,
    "near_obstacle_scan_y_ratio": 0.54,
    "near_obstacle_roi_top_ratio": 0.48,
    "near_obstacle_roi_bottom_ratio": 0.94,
    "near_obstacle_roi_x_margin_ratio": 0.08,
    "near_obstacle_min_area": 700.0,
    "near_obstacle_min_width": 28.0,
    "near_obstacle_min_height": 18.0,
}

LINE_FOLLOW_PROFILE = {
    "enable": True,
    "white_min": 145.0,
    "scan_top_ratio": 0.48,
    "scan_bottom_ratio": 0.86,
    "scan_count": 9,
    "row_band": 3,
    "min_segment_width": 3.0,
    "max_segment_width": 70.0,
    "initial_center_max_offset": 0.40,
    "max_center_jump_ratio": 0.24,
    "min_points_per_camera": 3,
    "min_y_span": 70.0,
    "near_y_ratio": 0.78,
    "far_y_ratio": 0.55,
    "min_confidence": 0.30,
    "offset_gain": 0.76,
    "heading_gain": 0.18,
    "max_correction": 0.34,
}

ESTIMATOR_PROFILE = {
    "image_center_x": 320.0,
    "x_scale": 320.0,
    "lost_confidence": 0.08,
    "min_center_points": 3,
    "min_good_points": 8,
    "min_y_span": 30.0,
    "min_y_span_good": 220.0,
    "min_road_width_for_conf": 20.0,
    "near_progress_max": 0.35,
    "far_progress_min": 0.60,
    "near_eval_progress": 0.15,
    "far_eval_progress": 0.75,
    "heading_eval_progress": 0.45,
    "poly2_min_points": 5,
    "curvature_full_points": 12,
    "curvature_min_y_span": 150.0,
    "heading_gain": 1.25,
    "curvature_gain": 1.45,
    "fallback_curvature_gain": 0.70,
    "max_fit_error": 0.22,
    "smooth_alpha": 0.28,
    "low_conf_extra_smoothing": 0.30,
    "min_smooth_alpha": 0.18,
    "max_smooth_alpha": 0.70,
    "curve_smooth_alpha": 0.46,
    "max_error_delta": 0.22,
    "max_heading_delta": 0.20,
    "max_curvature_delta": 0.18,
    "lost_lateral_decay": 0.85,
    "lost_heading_decay": 0.78,
    "lost_curvature_decay": 0.76,
    "lost_lookahead_decay": 0.82,
    "timestamp_reset_gap": 2.0,
}

CONTROL = {
    "base_speed": 0.96,
    "max_speed": 1.00,
    "min_speed": 0.16,
    "straight_curve_max": 0.12,
    "straight_offset_max": 0.12,
    "straight_heading_max": 0.28,
    "straight_lost_steering_max": 0.12,
    "straight_memory_frames": 48,
    "straight_speed": 0.95,
    "straight_lost_speed": 0.92,
    "start_caution_seconds": 0.8,
    "start_speed": 0.36,
    "lost_confidence": 0.10,
    "recovery_confidence": 0.28,
    "lost_speed": 0.28,
    "recovery_speed": 0.44,
    "hard_turn_speed": 0.38,
    "hard_turn_center_speed_bonus": 0.20,
    "correction_speed": 0.58,
    "hard_turn_threshold": 0.20,
    "correction_error": 0.25,
    "recovery_frames": 4,
    "risk_curve_weight": 0.42,
    "risk_offset_weight": 0.28,
    "risk_confidence_weight": 0.22,
    "risk_lost_weight": 0.80,
    "near_weight_base": 0.90,
    "near_weight_offset_boost": 0.55,
    "far_weight_base": 0.75,
    "far_weight_curve_boost": 0.36,
    "far_conflict_offset_start": 0.18,
    "far_conflict_offset_scale": 2.00,
    "far_conflict_min_scale": 0.22,
    "gain_lateral": 0.80,
    "gain_lookahead": 0.72,
    "gain_heading": 0.72,
    "gain_curve": 0.12,
    "gain_lateral_nonlinear": 0.22,
    "gain_curve_nonlinear": 0.02,
    "turn_in_floor": 0.55,
    "turn_in_lateral_ref": 0.30,
    "turn_in_heading_ref": 0.45,
    "steering_deadzone": 0.015,
    "max_abs_steering": 0.76,
    "hard_turn_steering_scale": 0.84,
    "steering_speed_cap_scale": 0.36,
    "inside_left_lateral_min": 0.05,
    "inside_left_heading_max": -0.24,
    "inside_left_curvature_max": -0.45,
    "inside_left_steering_limit": -0.40,
    "curve_slowdown": 0.64,
    "curve_power": 1.18,
    "offset_slowdown": 0.38,
    "offset_power": 1.25,
    "min_confidence_factor": 0.58,
    "steering_slowdown": 0.18,
    "steering_power": 1.15,
    "steering_smoothing_cruise": 0.16,
    "steering_smoothing_turn": 0.14,
    "steering_smoothing_correction": 0.14,
    "steering_smoothing_recovery": 0.28,
    "max_steering_delta": 0.46,
    "max_speed_increase_per_sec": 1.85,
    "max_speed_decrease_per_sec": 4.80,
    "escape_min_confidence": 0.48,
    "escape_curve_threshold": 0.45,
    "escape_steering_threshold": 0.70,
    "escape_offset_threshold": 0.62,
    "escape_offset_speed_threshold": 0.36,
    "escape_offset_heading_abs_max": 0.18,
    "escape_offset_curve_abs_max": 0.30,
    "escape_offset_lookahead_alignment": 0.30,
    "escape_offset_trigger_frames": 14,
    "escape_low_speed_threshold": 0.22,
    "escape_low_speed_trigger_frames": 120,
    "escape_signature_delta": 0.13,
    "escape_trigger_frames": 18,
    "escape_turn_frames": 24,
    "escape_turn_steering": 0.58,
    "escape_turn_speed": 0.62,
    "escape_offset_frames": 72,
    "escape_offset_steering": 0.74,
    "escape_offset_speed": 0.78,
    "escape_low_speed_frames": 120,
    "escape_low_speed_steering": 0.74,
    "escape_low_speed_speed": 0.90,
    "escape_pinned_lateral_min": 0.45,
    "escape_pinned_steering_min": 0.55,
    "escape_pinned_speed_max": 0.55,
    "escape_pinned_trigger_frames": 20,
    "escape_pinned_frames": 28,
    "escape_pinned_steering": 0.80,
    "escape_pinned_speed": 0.62,
    "nominal_dt": 0.032,
    "timestamp_reset_gap": 2.0,
}

BASIC_CONTROL_OVERRIDES = {
    "lost_speed": 0.24,
    "recovery_speed": 0.38,
    "straight_speed": 1.00,
    "straight_lost_speed": 1.00,
    "hard_turn_speed": 0.30,
    "hard_turn_center_speed_bonus": 0.30,
    "correction_speed": 0.50,
    "far_conflict_offset_start": 0.00,
    "far_conflict_offset_scale": 3.20,
    "far_conflict_min_scale": 0.05,
    "gain_lateral": 0.86,
    "gain_lookahead": 0.68,
    "gain_heading": 0.68,
    "gain_curve": 0.10,
    "near_weight_offset_boost": 0.58,
    "far_weight_curve_boost": 0.28,
    "max_abs_steering": 0.74,
    "hard_turn_steering_scale": 0.78,
    "steering_speed_cap_scale": 0.42,
    "curve_slowdown": 0.70,
    "curve_power": 1.35,
    "steering_slowdown": 0.28,
    "max_speed_increase_per_sec": 1.60,
    "max_speed_decrease_per_sec": 2.20,
}


def get_profile(name: str) -> dict:
    """读取控制 profile。

    功能：为顶层控制器提供当前唯一维护的控制参数。
    参数：`name` 保留兼容构建脚本和提交文件中的 fastest/safe 标记。
    返回：`CONTROL` 参数字典的浅拷贝。
    逻辑：所有模式都返回同一套参数，便于先集中优化一个目标。
    """

    del name
    return dict(CONTROL)



# ---- opponent.py ----

"""对手车辆感知模块。

功能概述：保留可提交的近处车身检测逻辑，供后续多车策略使用。
输入输出：输入单张 BGR 图像，输出是否检测到近距离车身遮挡。
处理流程：截取下半部中间 ROI，提取高饱和、亮白和近黑候选块，再用连通域尺寸过滤噪声。
"""




def detect_near_vehicle_obstacle(image: np.ndarray, profile: dict | None = None) -> bool:
    """检测近处是否有大块车身遮挡。

    功能：识别发车格静止车辆或近距离对手车这类大块遮挡。
    参数：`image` 是单张 BGR 摄像头图像，`profile` 可覆盖默认检测参数。
    返回：检测到较大车身色块时返回 True。
    逻辑：只看图像下半部中间区域，用高饱和、亮白和近黑色块做候选，再用连通域面积过滤车道线。
    """

    params = OPPONENT_PROFILE if profile is None else profile
    height, width = image.shape[:2]
    y0 = int(height * params["near_obstacle_roi_top_ratio"])
    y1 = int(height * params["near_obstacle_roi_bottom_ratio"])
    x_margin = int(width * params["near_obstacle_roi_x_margin_ratio"])
    roi = image[y0:y1, x_margin : width - x_margin]
    if roi.size == 0:
        return False

    gray = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    saturation = hsv[:, :, 1]
    value = hsv[:, :, 2]
    candidate = (
        ((saturation > 85) & (value > 80))
        | ((gray > 135) & (saturation < 95))
        | ((gray < 35) & (value < 55))
    ).astype(np.uint8) * 255

    kernel = np.ones((5, 5), dtype=np.uint8)
    candidate = cv2.morphologyEx(candidate, cv2.MORPH_OPEN, kernel, iterations=1)
    count, _, stats, _ = cv2.connectedComponentsWithStats(candidate, 8)
    min_area = float(params["near_obstacle_min_area"])
    min_width = float(params["near_obstacle_min_width"])
    min_height = float(params["near_obstacle_min_height"])
    for index in range(1, count):
        _, _, comp_width, comp_height, area = stats[index]
        if area >= min_area and comp_width >= min_width and comp_height >= min_height:
            return True
    return False



# ---- perception.py ----

"""视觉感知模块。

功能概述：从左右摄像头图像中分割道路表面，并沿扫描线跟踪可行驶走廊。
输入输出：输入 BGR 图像和可选时间戳，输出 `PerceptionObs`。
处理流程：估计道路颜色，生成道路 mask，逐行选择连续走廊，再融合左右摄像头结果。
"""




_RED_ENVIRONMENT_FLAG = 32


@dataclass
class _CameraScan:
    """单侧摄像头扫描结果。

    功能：保存单张图像的中心点、边界点、道路宽度、置信度和调试标记。
    参数：字段由 `_scan_image()` 生成。
    返回：内部 dataclass。
    逻辑：融合阶段只读取这些稳定字段，不依赖扫描过程的中间变量。
    """

    center_points: np.ndarray
    left_edge_points: np.ndarray
    right_edge_points: np.ndarray
    road_width_est: float
    confidence: float
    debug_flags: int = 0


def _empty_points() -> np.ndarray:
    return np.empty((0, 2), dtype=np.float32)


def _empty_scan(debug_flags: int = 1) -> _CameraScan:
    points = _empty_points()
    return _CameraScan(points, points, points, 0.0, 0.0, debug_flags=debug_flags)


def _empty_obs(debug_flags: int = 1) -> PerceptionObs:
    points = _empty_points()
    return PerceptionObs(points, points, points, 0.0, 0.0, debug_flags=debug_flags)


def _valid_image(image) -> bool:
    """检查输入是否是三通道 BGR 图像。"""

    return image is not None and hasattr(image, "shape") and len(image.shape) == 3 and image.shape[2] == 3


def _road_color_from_patch(lab_roi: np.ndarray) -> np.ndarray:
    """估计道路表面 Lab 颜色。

    功能：从 ROI 底部中心 patch 估计道路颜色。
    参数：`lab_roi` 是中下部 ROI 的 Lab 图像。
    返回：三通道 Lab 中位数颜色。
    逻辑：中位数能降低车道线、阴影和零星高光对颜色估计的影响。
    """

    height, width = lab_roi.shape[:2]
    y0 = int(height * 0.72)
    y1 = max(y0 + 1, int(height * 0.96))
    x_margin = int(width * 0.18)
    x0 = max(width // 2 - x_margin, 0)
    x1 = min(width // 2 + x_margin, width)
    patch = lab_roi[y0:y1, x0:x1]
    return np.median(patch.reshape(-1, 3).astype(np.float32), axis=0)


def _is_red_environment(image: np.ndarray) -> bool:
    """判断当前摄像头是否处在 complex 的红色场地环境。"""

    height = image.shape[0]
    roi = image[int(height * 0.30) : int(height * 0.88), :]
    if roi.size == 0:
        return False
    hsv = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    hue = hsv[:, :, 0]
    saturation = hsv[:, :, 1]
    value = hsv[:, :, 2]
    red = ((hue < 12) | (hue > 168)) & (saturation > 80) & (value > 50)
    red_ratio = float(np.count_nonzero(red)) / max(float(red.size), 1.0)
    return red_ratio >= VISION_PROFILE["red_world_min_ratio"]


def _build_masks(image: np.ndarray, timestamp=None) -> tuple[np.ndarray, np.ndarray, float, float, bool]:
    """生成道路表面 mask 和边缘 fallback mask。

    功能：优先用暗灰低饱和特征分割沥青路面，并单独保留 Canny 边缘作为兜底。
    参数：`image` 是单张 BGR 图像。
    返回：完整尺寸的 `road_mask`、`edge_mask`、灰度纹理分数、主 mask 命中率和近处障碍标记。
    逻辑：暗灰 mask 分割低饱和灰色沥青；草地是高饱和绿，统一从道路 mask 扣除，
    避免颜色种子落在草上时把整片草当成路；边缘不混入主 mask，避免把背景强边缘误当成道路表面。
    """

    height = image.shape[0]
    top = int(height * VISION_PROFILE["roi_top_ratio"])
    roi = image[top:, :, :]

    gray_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)
    hsv_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
    dark_road_roi = (
        (gray_roi >= VISION_PROFILE["road_gray_min"])
        & (gray_roi <= VISION_PROFILE["road_gray_max"])
        & (hsv_roi[:, :, 1] <= VISION_PROFILE["road_sat_max"])
    ).astype(np.uint8) * 255

    # 草地 mask：高饱和绿。沥青是低饱和灰，必不落在此区间；用于从道路 mask 中扣除草地。
    grass_roi = (
        (hsv_roi[:, :, 0] >= VISION_PROFILE["grass_hue_min"])
        & (hsv_roi[:, :, 0] <= VISION_PROFILE["grass_hue_max"])
        & (hsv_roi[:, :, 1] >= VISION_PROFILE["grass_sat_min"])
        & (hsv_roi[:, :, 2] >= VISION_PROFILE["grass_value_min"])
    )

    lab_roi = cv2.cvtColor(roi, cv2.COLOR_BGR2LAB).astype(np.float32)
    road_lab = _road_color_from_patch(lab_roi)
    distance = np.sqrt(np.sum((lab_roi - road_lab) ** 2, axis=2))
    color_roi = (distance <= VISION_PROFILE["road_lab_threshold"]).astype(np.uint8) * 255

    dark_fill_ratio = float(np.count_nonzero(dark_road_roi)) / max(float(dark_road_roi.size), 1.0)
    if dark_fill_ratio >= VISION_PROFILE["dark_mask_min_fill"]:
        road_roi = dark_road_roi.copy()
    else:
        # 暗沥青 mask 稀疏（远处只剩细条路面）才回退颜色 mask；并入暗 mask 保住那条沥青，
        # 颜色种子可能落在草上，靠下一步扣草兜底。
        road_roi = color_roi | dark_road_roi

    # 统一扣除草地：无论用哪条 mask，草都不算路。偏出赛道正对草地时 mask 会塌到近空 → 低置信 → lost。
    road_roi[grass_roi] = 0

    # checkpoint 蓝色门是半透明、横跨在赛道上的——门后就是可行驶路面。把门并入道路 mask，
    # 避免它把走廊在中段截断（弯道里只剩近处点 → edge fallback → 朝栏杆打/剐蹭）。
    # 注意：这会让部分含天空的帧 mask 饱和 → 被判 lost，离线 per-frame lost 率会明显升高。
    # 但 lost 时车是直线滑行（不停车、不偏出），这是良性的——实车验证（R005/C003）是迄今最好
    # 的一版：蓝门前大拐弯和过弯剐蹭都消失。**不要用离线 lost 率否决这版**（详见 notes.md R005）。
    barrier_roi = (
        (hsv_roi[:, :, 0] >= VISION_PROFILE["barrier_hue_min"])
        & (hsv_roi[:, :, 0] <= VISION_PROFILE["barrier_hue_max"])
        & (hsv_roi[:, :, 1] >= VISION_PROFILE["barrier_sat_min"])
        & (hsv_roi[:, :, 2] >= VISION_PROFILE["barrier_value_min"])
        & (hsv_roi[:, :, 2] <= VISION_PROFILE["barrier_value_max"])
    )
    road_roi[barrier_roi] = 255

    kernel = np.ones((5, 5), dtype=np.uint8)
    road_roi = cv2.morphologyEx(road_roi, cv2.MORPH_OPEN, kernel, iterations=1)
    road_roi = cv2.morphologyEx(road_roi, cv2.MORPH_CLOSE, kernel, iterations=2)

    blurred = cv2.GaussianBlur(gray_roi, (5, 5), 0)
    edge_roi = cv2.Canny(blurred, 45, 120)

    road_mask = np.zeros(image.shape[:2], dtype=np.uint8)
    edge_mask = np.zeros(image.shape[:2], dtype=np.uint8)
    road_mask[top:, :] = road_roi
    edge_mask[top:, :] = edge_roi

    texture_score = clamp(float(np.std(gray_roi)) / VISION_PROFILE["texture_gray_std_scale"], 0.0, 1.0)
    mask_fill_ratio = float(np.count_nonzero(road_roi)) / max(float(road_roi.size), 1.0)
    near_obstacle = False
    if OPPONENT_PROFILE["enable_opponent_avoidance"]:
        try:
            current_time = float(timestamp)
        except (TypeError, ValueError):
            current_time = 0.0
        near_obstacle = (
            current_time >= OPPONENT_PROFILE["near_obstacle_min_timestamp"]
            and detect_near_vehicle_obstacle(image, OPPONENT_PROFILE)
        )
    return road_mask, edge_mask, texture_score, mask_fill_ratio, near_obstacle


def _segments_from_active(active: np.ndarray) -> list[tuple[int, int]]:
    """把一维布尔扫描结果转成连续区间。"""

    if active.size == 0:
        return []
    padded = np.concatenate(([False], active.astype(bool), [False]))
    changes = np.flatnonzero(padded[1:] != padded[:-1])
    return [(int(changes[i]), int(changes[i + 1] - 1)) for i in range(0, len(changes), 2)]


def _merge_close_segments(segments: list[tuple[int, int]], max_gap: int | None = None) -> list[tuple[int, int]]:
    """合并被车道虚线或护栏细缝切开的相邻道路段。"""

    if not segments:
        return []
    if max_gap is None:
        max_gap = int(VISION_PROFILE["max_segment_gap"])
    merged = [segments[0]]
    for left, right in segments[1:]:
        prev_left, prev_right = merged[-1]
        if left - prev_right - 1 <= max_gap:
            merged[-1] = (prev_left, right)
        else:
            merged.append((left, right))
    return merged


def _road_segments(mask: np.ndarray, y: int, row_band: int, max_gap: int | None = None) -> list[tuple[int, int]]:
    """从道路 mask 的水平横带中提取连续道路区间。"""

    y0 = max(int(y) - row_band, 0)
    y1 = min(int(y) + row_band + 1, mask.shape[0])
    band = mask[y0:y1, :]
    min_hits = max(1, int(np.ceil(band.shape[0] * 0.45)))
    active = np.count_nonzero(band, axis=0) >= min_hits
    return _merge_close_segments(_segments_from_active(active), max_gap=max_gap)


def _edge_fallback_segments(edge_mask: np.ndarray, y: int, row_band: int) -> list[tuple[int, int]]:
    """从边缘横带中推断候选走廊。

    功能：在道路 mask 没有可用区间时，用相邻边缘之间的区域做兜底。
    参数：`edge_mask` 是 Canny 结果，`y` 是扫描线，`row_band` 是横带半宽。
    返回：候选 `(left, right)` 区间。
    逻辑：只取相邻边缘，避免随机纹理生成大量跨越式组合。
    """

    y0 = max(int(y) - row_band, 0)
    y1 = min(int(y) + row_band + 1, edge_mask.shape[0])
    band = edge_mask[y0:y1, :]
    active = np.count_nonzero(band, axis=0) > 0
    edge_segments = _segments_from_active(active)
    if len(edge_segments) < 2:
        return []

    edge_centers = [int((left + right) * 0.5) for left, right in edge_segments]
    return [(edge_centers[index], edge_centers[index + 1]) for index in range(len(edge_centers) - 1)]


def _filter_segments(
    segments: list[tuple[int, int]],
    width: int,
    max_width_ratio: float | None = None,
) -> list[tuple[int, int]]:
    """按道路宽度约束过滤候选区间。"""

    min_width = float(VISION_PROFILE["min_segment_width"])
    if max_width_ratio is None:
        max_width_ratio = VISION_PROFILE["max_segment_width_ratio"]
    max_width = float(width) * float(max_width_ratio)
    filtered = []
    for left, right in segments:
        segment_width = float(right - left + 1)
        if min_width <= segment_width <= max_width:
            filtered.append((left, right))
    return filtered


def _filter_fallback_segments(
    segments: list[tuple[int, int]],
    width: int,
    previous_center: float,
    has_previous: bool,
) -> list[tuple[int, int]]:
    """过滤容易由白线碎片生成的窄 fallback 走廊。

    功能：避免近处孤立车道线/接缝小段把扫描 seed 拉到内侧。
    参数：`segments` 是边缘 fallback 候选，`previous_center` 是上一条中心。
    返回：过滤后的候选区间。
    逻辑：宽 fallback 正常保留；窄 fallback 只有在靠近画面中心或延续上一中心时才可用。
    """

    if not segments:
        return []

    min_width = float(VISION_PROFILE["fallback_min_segment_width"])
    initial_center_limit = float(width) * VISION_PROFILE["fallback_initial_center_max_offset"]
    narrow_jump_limit = float(width) * VISION_PROFILE["fallback_narrow_jump_max_ratio"]
    image_center = float(width) * 0.5

    filtered = []
    for left, right in segments:
        segment_width = float(right - left + 1)
        center = (float(left) + float(right)) * 0.5
        if segment_width >= min_width:
            filtered.append((left, right))
        elif not has_previous and abs(center - image_center) <= initial_center_limit:
            filtered.append((left, right))
        elif has_previous and abs(center - previous_center) <= narrow_jump_limit:
            filtered.append((left, right))
    return filtered


def _localize_wide_segment(
    segment: tuple[int, int],
    previous_center: float,
    width: int,
    enabled: bool = True,
) -> tuple[int, int]:
    """把过宽道路段截成上一扫描中心附近的局部走廊。

    功能：处理复合弯中多条道路被暗色 mask 连成一片的情况。
    参数：`segment` 是候选暗区，`previous_center` 是近处已选中心，`width` 是图像宽度。
    返回：可能被截窄后的 `(left, right)`。
    逻辑：正常宽度道路不处理；过宽时保留靠近上一中心的一段，避免用整块暗区中心。
    """

    left, right = segment
    segment_width = float(right - left + 1)
    if not enabled:
        return segment
    if segment_width <= float(width) * VISION_PROFILE["wide_segment_localize_ratio"]:
        return segment

    target_width = max(
        VISION_PROFILE["min_segment_width"],
        float(width) * VISION_PROFILE["wide_segment_window_ratio"],
    )
    half = target_width * 0.5
    center = previous_center
    center = clamp(center, float(left) + half, float(right) - half)
    localized_left = max(left, int(round(center - half)))
    localized_right = min(right, int(round(center + half)))
    if localized_right <= localized_left:
        return segment
    return localized_left, localized_right


def _pick_segment(
    road_mask: np.ndarray,
    edge_mask: np.ndarray,
    y: int,
    previous_center: float,
    has_previous: bool,
    near_obstacle: bool,
    wide_localize_enabled: bool,
) -> tuple[tuple[int, int] | None, bool]:
    """选择当前扫描线的最佳走廊 segment。

    功能：优先从道路表面 mask 选连续区间，失败时再用边缘区间兜底。
    参数：`road_mask` 和 `edge_mask` 是完整尺寸 mask，`previous_center` 是上一条有效扫描线中心。
    返回：选中的 `(left, right)` 和是否使用边缘 fallback。
    逻辑：候选区间必须满足宽度约束，并尽量靠近上一条有效扫描线。
    """

    width = road_mask.shape[1]
    row_band = int(VISION_PROFILE["row_band"])
    max_width_ratio = (
        VISION_PROFILE["max_segment_width_ratio"]
        if wide_localize_enabled
        else VISION_PROFILE["early_max_segment_width_ratio"]
    )
    max_gap = None
    if near_obstacle and y >= int(road_mask.shape[0] * OPPONENT_PROFILE["near_obstacle_scan_y_ratio"]):
        max_gap = int(OPPONENT_PROFILE["near_obstacle_segment_gap"])
    candidates = _filter_segments(
        _road_segments(road_mask, y, row_band, max_gap=max_gap),
        width,
        max_width_ratio=max_width_ratio,
    )
    used_fallback = False
    if not candidates:
        candidates = _filter_segments(
            _edge_fallback_segments(edge_mask, y, row_band),
            width,
            max_width_ratio=max_width_ratio,
        )
        candidates = _filter_fallback_segments(candidates, width, previous_center, has_previous)
        used_fallback = bool(candidates)
    if not candidates:
        return None, used_fallback

    best = min(candidates, key=lambda item: abs(((item[0] + item[1]) * 0.5) - previous_center))
    best = _localize_wide_segment(best, previous_center, width, enabled=wide_localize_enabled)
    center = (best[0] + best[1]) * 0.5
    max_jump = float(width) * VISION_PROFILE["max_center_jump_ratio"]
    if has_previous and abs(center - previous_center) > max_jump:
        return None, used_fallback
    return best, used_fallback


def _score_scan(
    centers: list[tuple[float, float]],
    widths: list[float],
    texture_score: float,
    mask_fill_ratio: float,
    fallback_count: int,
) -> tuple[float, int]:
    """计算单侧摄像头置信度。

    功能：综合有效扫描线、宽度稳定性、中心稳定性和纹理分数。
    参数：扫描点、宽度序列、纹理分数、mask 命中率和 fallback 次数。
    返回：置信度和调试标记。
    逻辑：有效线太少、整图近似全不命中时重降权；饱和 mask 保留中等降权，
    避免远处路面可见但底部草地铺满 ROI 时整段丢线。
    """

    debug_flags = 0
    scan_count = float(VISION_PROFILE["scan_count"])
    valid_count = len(centers)
    valid_ratio = valid_count / max(scan_count, 1.0)

    width_arr = np.array(widths, dtype=np.float32)
    width_median = max(float(np.median(width_arr)), 1.0)
    width_stability = clamp(1.0 - float(np.std(width_arr)) / width_median, 0.0, 1.0)

    center_arr = np.array([point[0] for point in centers], dtype=np.float32)
    if center_arr.size >= 2:
        center_jump = np.abs(np.diff(center_arr))
        center_stability = clamp(
            1.0 - float(np.mean(center_jump)) / (640.0 * VISION_PROFILE["max_center_jump_ratio"]),
            0.0,
            1.0,
        )
    else:
        center_stability = 0.0

    confidence = (
        valid_ratio * 0.38
        + width_stability * 0.22
        + center_stability * 0.22
        + texture_score * 0.18
    )

    min_valid = int(VISION_PROFILE["min_valid_scans"])
    if valid_count < min_valid:
        confidence *= valid_count / max(float(min_valid), 1.0)
        debug_flags |= 1
    if mask_fill_ratio < 0.015:
        confidence *= VISION_PROFILE["empty_mask_confidence_scale"]
        debug_flags |= 4
    elif mask_fill_ratio > 0.92:
        confidence *= VISION_PROFILE["saturated_mask_confidence_scale"]
        debug_flags |= 4
    if fallback_count:
        confidence *= max(0.55, 1.0 - 0.06 * fallback_count)
        debug_flags |= 2

    return clamp(confidence, 0.0, 1.0), debug_flags


def _scan_image(image: np.ndarray, timestamp=None) -> _CameraScan:
    """按扫描线跟踪单张图像的道路走廊。

    功能：输出中心点、左右边界点、道路宽度和置信度。
    参数：`image` 是单个摄像头 BGR 图像，`timestamp` 用于限制末段障碍处理。
    返回：`_CameraScan`。
    逻辑：从近处向远处扫描，每条线选择离上一条有效中心最近的连续道路 segment。
    """

    if not _valid_image(image):
        return _empty_scan()

    road_mask, edge_mask, texture_score, mask_fill_ratio, near_obstacle = _build_masks(image, timestamp)
    red_environment = _is_red_environment(image)
    wide_localize_enabled = red_environment
    height, width = road_mask.shape
    rows = np.linspace(
        int(height * VISION_PROFILE["scan_bottom_ratio"]),
        int(height * VISION_PROFILE["scan_top_ratio"]),
        int(VISION_PROFILE["scan_count"]),
        dtype=np.int32,
    )

    centers = []
    left_edges = []
    right_edges = []
    widths = []
    previous_center = width * 0.5
    has_previous = False
    fallback_count = 0

    for y in rows:
        segment, used_fallback = _pick_segment(
            road_mask,
            edge_mask,
            int(y),
            previous_center,
            has_previous,
            near_obstacle,
            wide_localize_enabled,
        )
        if segment is None:
            continue
        left, right = segment
        center = (left + right) * 0.5
        road_width = float(right - left + 1)
        centers.append((center, float(y)))
        left_edges.append((float(left), float(y)))
        right_edges.append((float(right), float(y)))
        widths.append(road_width)
        previous_center = center
        has_previous = True
        if used_fallback:
            fallback_count += 1

    if not centers:
        debug_flags = 4 if mask_fill_ratio < 0.015 or mask_fill_ratio > 0.92 else 1
        return _empty_scan(debug_flags=debug_flags)

    confidence, debug_flags = _score_scan(centers, widths, texture_score, mask_fill_ratio, fallback_count)
    if red_environment:
        debug_flags |= _RED_ENVIRONMENT_FLAG
    return _CameraScan(
        np.array(centers, dtype=np.float32),
        np.array(left_edges, dtype=np.float32),
        np.array(right_edges, dtype=np.float32),
        float(np.median(np.array(widths, dtype=np.float32))),
        confidence,
        debug_flags=debug_flags,
    )


def _usable(scan: _CameraScan) -> bool:
    """判断单侧扫描结果是否足以参与融合。"""

    return scan.center_points.size > 0 and scan.confidence >= VISION_PROFILE["min_camera_confidence"]


def _near_center(scan: _CameraScan) -> float:
    """读取最靠近车辆的扫描中心。"""

    if scan.center_points.size == 0:
        return 320.0
    return float(scan.center_points[0, 0])


def _to_obs(scan: _CameraScan, debug_flags: int | None = None) -> PerceptionObs:
    """把单侧扫描结果转换为公开观测结构。"""

    flags = scan.debug_flags if debug_flags is None else debug_flags
    return PerceptionObs(
        scan.center_points,
        scan.left_edge_points,
        scan.right_edge_points,
        scan.road_width_est,
        clamp(scan.confidence, 0.0, 1.0),
        debug_flags=flags,
    )


def _fuse_scans(left_scan: _CameraScan, right_scan: _CameraScan) -> PerceptionObs:
    """融合左右摄像头扫描结果。

    功能：根据单侧可用性、近处中心一致性和置信度选择或合并观测。
    参数：`left_scan` 和 `right_scan` 是两侧扫描结果。
    返回：融合后的 `PerceptionObs`。
    逻辑：单侧有效时直接使用；双侧冲突时选高置信度；一致时合并点集并平均置信度。
    """

    left_ok = _usable(left_scan)
    right_ok = _usable(right_scan)
    if left_ok and not right_ok:
        return _to_obs(left_scan)
    if right_ok and not left_ok:
        return _to_obs(right_scan)
    if not left_ok and not right_ok:
        return _empty_obs(debug_flags=left_scan.debug_flags | right_scan.debug_flags | 1)

    center_gap = abs(_near_center(left_scan) - _near_center(right_scan))
    merge_gap = 640.0 * VISION_PROFILE["fusion_merge_gap"]
    merge_confidence = VISION_PROFILE["fusion_merge_min_confidence"]
    confidence_gap = abs(left_scan.confidence - right_scan.confidence)
    if (
        center_gap >= merge_gap
        or left_scan.confidence < merge_confidence
        or right_scan.confidence < merge_confidence
    ):
        chosen = left_scan if left_scan.confidence >= right_scan.confidence else right_scan
        flags = chosen.debug_flags
        if center_gap > 640.0 * VISION_PROFILE["fusion_max_offset_gap"]:
            flags |= 8
        if confidence_gap < VISION_PROFILE["fusion_confidence_margin"]:
            flags |= 16
        return _to_obs(chosen, debug_flags=flags)

    center_points = np.concatenate([left_scan.center_points, right_scan.center_points], axis=0)
    left_edge_points = np.concatenate([left_scan.left_edge_points, right_scan.left_edge_points], axis=0)
    right_edge_points = np.concatenate([left_scan.right_edge_points, right_scan.right_edge_points], axis=0)
    weights = np.array([len(left_scan.center_points), len(right_scan.center_points)], dtype=np.float32)
    confidences = np.array([left_scan.confidence, right_scan.confidence], dtype=np.float32)
    width_values = np.array([left_scan.road_width_est, right_scan.road_width_est], dtype=np.float32)
    confidence = float(np.average(confidences, weights=weights))
    road_width_est = float(np.average(width_values, weights=weights))
    return PerceptionObs(
        center_points,
        left_edge_points,
        right_edge_points,
        road_width_est,
        clamp(confidence, 0.0, 1.0),
        debug_flags=left_scan.debug_flags | right_scan.debug_flags,
    )


def extract_observation(left_img, right_img, timestamp=None) -> PerceptionObs:
    """提取左右摄像头的赛道观测。

    功能：输出中心点、边界点、道路宽度估计和感知置信度。
    参数：`left_img` 与 `right_img` 是平台传入的 BGR 图像，`timestamp` 预留给后续时间上下文。
    返回：`PerceptionObs`。
    逻辑：分别扫描左右图像；单侧有效则使用单侧，双侧一致则合并，双侧冲突则选择高置信度结果。
    """

    left_scan = _scan_image(left_img, timestamp) if _valid_image(left_img) else _empty_scan()
    right_scan = _scan_image(right_img, timestamp) if _valid_image(right_img) else _empty_scan()
    return _fuse_scans(left_scan, right_scan)



# ---- estimator.py ----

"""赛道几何估计模块。

功能概述：把感知中心点转换成稳定的赛道状态。
输入输出：输入 `PerceptionObs` 和时间戳，输出 `TrackState`。
处理流程：清洗中心点，按 progress 拟合中心线，估计偏移、朝向和曲率，再按置信度平滑。
"""



_LAST_TRACK = TrackState(0.0, 0.0, 0.0, 0.0, 0.0, True)
_LAST_TIMESTAMP = None
_LAST_RED_ENVIRONMENT = False
_RED_ENVIRONMENT_STREAK = 0
_RED_ENVIRONMENT_FLAG = 32
_RED_ENVIRONMENT_LATCH_FRAMES = 3


def _lost_track(confidence: float, red_environment: bool | None = None) -> TrackState:
    """生成丢线状态。

    功能：保留上一帧估计的衰减值，避免控制量突然归零。
    参数：`confidence` 是当前可用的低置信度。
    返回：`lost=True` 的 `TrackState`。
    逻辑：各几何量使用独立衰减参数，置信度裁剪到合法范围。
    """

    if red_environment is None:
        red_environment = _LAST_TRACK.red_environment
    return TrackState(
        _LAST_TRACK.lateral_error * ESTIMATOR_PROFILE["lost_lateral_decay"],
        _LAST_TRACK.heading_error * ESTIMATOR_PROFILE["lost_heading_decay"],
        _LAST_TRACK.curvature * ESTIMATOR_PROFILE["lost_curvature_decay"],
        _LAST_TRACK.lookahead_error * ESTIMATOR_PROFILE["lost_lookahead_decay"],
        clamp(confidence, 0.0, ESTIMATOR_PROFILE["lost_confidence"]),
        True,
        red_environment,
    )


def _clean_points(points) -> np.ndarray:
    """清洗感知中心点。

    功能：把输入转为 `float32` 的 `N x 2` 数组，并过滤 NaN / inf。
    参数：`points` 是 `PerceptionObs.center_points`。
    返回：只含有限坐标的二维数组。
    逻辑：异常形状直接返回空数组，由上层进入 lost。
    """

    try:
        array = np.asarray(points, dtype=np.float32)
    except (TypeError, ValueError):
        return np.empty((0, 2), dtype=np.float32)
    if array.ndim != 2 or array.shape[1] != 2:
        return np.empty((0, 2), dtype=np.float32)
    return array[np.isfinite(array).all(axis=1)]


def _normalize_points(points: np.ndarray) -> tuple[np.ndarray, np.ndarray, float]:
    """把图像坐标转换成横向误差和前后进度。

    功能：固定图像中心为 320，把 x 归一化到 `[-1, 1]`，把 y 转成 progress。
    参数：`points` 是清洗后的中心点。
    返回：`x_norm`、`progress` 和 y 跨度。
    逻辑：progress=0 表示近处，progress=1 表示远处。
    """

    y = points[:, 1].astype(np.float32)
    y_min = float(np.min(y))
    y_max = float(np.max(y))
    y_span = max(y_max - y_min, 0.0)
    progress = (y_max - y) / max(y_span, 1.0)

    x = points[:, 0].astype(np.float32)
    x_norm = (x - ESTIMATOR_PROFILE["image_center_x"]) / ESTIMATOR_PROFILE["x_scale"]
    x_norm = np.clip(x_norm, -1.0, 1.0)
    return x_norm.astype(np.float32), progress.astype(np.float32), y_span


def _fit_centerline(progress: np.ndarray, x_norm: np.ndarray) -> tuple[np.ndarray, int]:
    """拟合归一化中心线。

    功能：用 progress 作为自变量拟合 `x_norm`。
    参数：`progress` 是前后进度，`x_norm` 是横向归一化中心。
    返回：`np.polyval()` 可用的系数和拟合阶数。
    逻辑：点数足够时用二次曲线，点数不足时用直线。
    """

    degree = 2 if len(progress) >= ESTIMATOR_PROFILE["poly2_min_points"] else 1
    coeffs = np.polyfit(progress, x_norm, deg=degree)
    return coeffs.astype(np.float32), degree


def _value_from_band(
    progress: np.ndarray,
    x_norm: np.ndarray,
    coeffs: np.ndarray,
    mask: np.ndarray,
    fallback_progress: float,
) -> float:
    """从指定 progress 区间估计横向误差。"""

    if np.any(mask):
        return float(np.median(x_norm[mask]))
    return float(np.polyval(coeffs, fallback_progress))


def _heading_from_fit(coeffs: np.ndarray, degree: int) -> float:
    """由中心线导数估计朝向误差。"""

    eval_progress = ESTIMATOR_PROFILE["heading_eval_progress"]
    if degree == 2:
        derivative = float(2.0 * coeffs[0] * eval_progress + coeffs[1])
    else:
        derivative = float(coeffs[0])
    return clamp(derivative * ESTIMATOR_PROFILE["heading_gain"], -1.0, 1.0)


def _curvature_trust(n_points: int, y_span: float, fit_score: float) -> float:
    """计算曲率可信度。

    功能：当扫描点少、纵向跨度小或拟合误差大时，二次项不可信，可信度趋近 0。
    参数：`n_points` 是中心点数，`y_span` 是纵向像素跨度，`fit_score` 是拟合质量分。
    返回：`[0, 1]` 的可信度。
    逻辑：远端被遮挡时只剩近处少量聚簇点，deg-2 二次系数是数值噪声（常被钳到 ±1、
    甚至符号相反——在全程右弯的赛道上凭空出现"满信心左弯"）。三项必须同时达标才信曲率。
    """

    span = max(ESTIMATOR_PROFILE["curvature_full_points"] - ESTIMATOR_PROFILE["poly2_min_points"], 1.0)
    n_score = clamp((float(n_points) - ESTIMATOR_PROFILE["poly2_min_points"]) / span, 0.0, 1.0)
    span_score = clamp(y_span / ESTIMATOR_PROFILE["curvature_min_y_span"], 0.0, 1.0)
    return clamp(n_score * span_score * clamp(fit_score, 0.0, 1.0), 0.0, 1.0)


def _curvature_from_fit(
    coeffs: np.ndarray,
    degree: int,
    lateral_error: float,
    lookahead_error: float,
    trust: float,
) -> float:
    """估计中心线曲率。

    功能：二次拟合时用二次项，其他情况用远近误差差值兜底，并按可信度收缩。
    参数：拟合系数、阶数、近处误差、远处误差和曲率可信度 `trust`。
    返回：右弯为正、左弯为负的曲率值。
    逻辑：用 `trust` 把不可信的二次系数收向 0，避免幻觉急弯；再裁剪到 `[-1, 1]`。
    """

    if degree == 2:
        value = float(coeffs[0]) * ESTIMATOR_PROFILE["curvature_gain"]
    else:
        value = (lookahead_error - lateral_error) * ESTIMATOR_PROFILE["fallback_curvature_gain"]
    return clamp(value * trust, -1.0, 1.0)


def _fit_error_score(progress: np.ndarray, x_norm: np.ndarray, coeffs: np.ndarray) -> float:
    """把中心线拟合误差转换成置信度分数。"""

    fitted = np.polyval(coeffs, progress)
    rmse = float(np.sqrt(np.mean((x_norm - fitted) ** 2)))
    return clamp(1.0 - rmse / ESTIMATOR_PROFILE["max_fit_error"], 0.0, 1.0)


def _geometry_confidence(obs: PerceptionObs, points: np.ndarray, y_span: float, fit_score: float) -> float:
    """计算几何置信度。

    功能：综合感知置信度、点数、y 覆盖范围、拟合误差和道路宽度。
    参数：`obs` 是感知结果，`points` 是清洗点，`y_span` 是纵向覆盖，`fit_score` 是拟合质量。
    返回：`[0, 1]` 内的几何置信度。
    逻辑：几何质量差时不会直接照抄感知置信度。
    """

    obs_score = clamp(obs.confidence, 0.0, 1.0)
    point_score = clamp(len(points) / float(ESTIMATOR_PROFILE["min_good_points"]), 0.0, 1.0)
    span_score = clamp(y_span / ESTIMATOR_PROFILE["min_y_span_good"], 0.0, 1.0)
    width_score = clamp(obs.road_width_est / ESTIMATOR_PROFILE["min_road_width_for_conf"], 0.0, 1.0)
    quality = (
        0.30
        + point_score * 0.20
        + span_score * 0.20
        + fit_score * 0.25
        + width_score * 0.05
    )
    confidence = obs_score * quality
    return clamp(min(confidence, obs_score + 0.20), 0.0, 1.0)


def _smooth_alpha(confidence: float) -> float:
    """按置信度选择普通误差平滑强度。"""

    low_conf = 1.0 - clamp(confidence, 0.0, 1.0)
    alpha = (
        ESTIMATOR_PROFILE["min_smooth_alpha"]
        + (ESTIMATOR_PROFILE["max_smooth_alpha"] - ESTIMATOR_PROFILE["min_smooth_alpha"]) * low_conf
        + ESTIMATOR_PROFILE["low_conf_extra_smoothing"] * low_conf
    )
    return clamp(alpha, ESTIMATOR_PROFILE["min_smooth_alpha"], ESTIMATOR_PROFILE["max_smooth_alpha"])


def _smooth_limited(previous: float, current: float, alpha: float, max_delta: float) -> float:
    """平滑单个值并限制单帧变化。"""

    smoothed = previous * alpha + current * (1.0 - alpha)
    delta = clamp(smoothed - previous, -max_delta, max_delta)
    return clamp(previous + delta, -1.0, 1.0)


def reset_estimator_state() -> None:
    """重置估计器跨帧状态。

    功能：让测试或新一轮仿真从干净状态开始。
    参数：无。
    返回：无。
    逻辑：清空上一帧几何状态和时间戳。
    """

    global _LAST_TRACK, _LAST_TIMESTAMP, _LAST_RED_ENVIRONMENT, _RED_ENVIRONMENT_STREAK
    _LAST_TRACK = TrackState(0.0, 0.0, 0.0, 0.0, 0.0, True)
    _LAST_TIMESTAMP = None
    _LAST_RED_ENVIRONMENT = False
    _RED_ENVIRONMENT_STREAK = 0


def _maybe_reset_estimator_by_timestamp(timestamp: float) -> None:
    """根据时间戳判断是否重置跨帧状态。"""

    if _LAST_TIMESTAMP is None:
        return
    elapsed = float(timestamp) - float(_LAST_TIMESTAMP)
    if elapsed < 0.0 or elapsed > ESTIMATOR_PROFILE["timestamp_reset_gap"]:
        reset_estimator_state()


def estimate_track(obs: PerceptionObs, timestamp: float) -> TrackState:
    """估计赛道几何状态。

    功能：把感知中心点转换成 policy 可直接使用的赛道状态。
    参数：`obs` 是感知结果，`timestamp` 是平台时间戳。
    返回：`TrackState`。
    逻辑：点集无效时返回衰减 lost 状态；有效时按 progress 拟合中心线并做自适应平滑。
    """

    global _LAST_TRACK, _LAST_TIMESTAMP, _LAST_RED_ENVIRONMENT, _RED_ENVIRONMENT_STREAK

    timestamp = float(timestamp)
    _maybe_reset_estimator_by_timestamp(timestamp)

    observed_red = bool(obs.debug_flags & _RED_ENVIRONMENT_FLAG)
    if observed_red:
        _RED_ENVIRONMENT_STREAK += 1
    elif not _LAST_RED_ENVIRONMENT:
        _RED_ENVIRONMENT_STREAK = 0
    if _RED_ENVIRONMENT_STREAK >= _RED_ENVIRONMENT_LATCH_FRAMES:
        _LAST_RED_ENVIRONMENT = True
    red_environment = observed_red or _LAST_RED_ENVIRONMENT

    points = _clean_points(obs.center_points)
    if len(points) < ESTIMATOR_PROFILE["min_center_points"] or obs.confidence < ESTIMATOR_PROFILE["lost_confidence"]:
        track = _lost_track(obs.confidence, red_environment)
        _LAST_TRACK = track
        _LAST_TIMESTAMP = timestamp
        return track

    x_norm, progress, y_span = _normalize_points(points)
    if y_span < ESTIMATOR_PROFILE["min_y_span"]:
        track = _lost_track(obs.confidence, red_environment)
        _LAST_TRACK = track
        _LAST_TIMESTAMP = timestamp
        return track

    coeffs, degree = _fit_centerline(progress, x_norm)
    lateral_error = clamp(
        _value_from_band(
            progress,
            x_norm,
            coeffs,
            progress <= ESTIMATOR_PROFILE["near_progress_max"],
            ESTIMATOR_PROFILE["near_eval_progress"],
        ),
        -1.0,
        1.0,
    )
    lookahead_error = clamp(
        _value_from_band(
            progress,
            x_norm,
            coeffs,
            progress >= ESTIMATOR_PROFILE["far_progress_min"],
            ESTIMATOR_PROFILE["far_eval_progress"],
        ),
        -1.0,
        1.0,
    )
    heading_error = _heading_from_fit(coeffs, degree)
    fit_score = _fit_error_score(progress, x_norm, coeffs)
    curvature_trust = _curvature_trust(len(points), y_span, fit_score)
    curvature = _curvature_from_fit(coeffs, degree, lateral_error, lookahead_error, curvature_trust)

    confidence = _geometry_confidence(obs, points, y_span, fit_score)
    if confidence < ESTIMATOR_PROFILE["lost_confidence"]:
        track = _lost_track(confidence, red_environment)
        _LAST_TRACK = track
        _LAST_TIMESTAMP = timestamp
        return track

    alpha = _smooth_alpha(confidence)
    curve_alpha = clamp(
        ESTIMATOR_PROFILE["curve_smooth_alpha"]
        + ESTIMATOR_PROFILE["low_conf_extra_smoothing"] * (1.0 - confidence),
        ESTIMATOR_PROFILE["min_smooth_alpha"],
        ESTIMATOR_PROFILE["max_smooth_alpha"],
    )
    track = TrackState(
        _smooth_limited(_LAST_TRACK.lateral_error, lateral_error, alpha, ESTIMATOR_PROFILE["max_error_delta"]),
        _smooth_limited(_LAST_TRACK.heading_error, heading_error, alpha, ESTIMATOR_PROFILE["max_heading_delta"]),
        _smooth_limited(_LAST_TRACK.curvature, curvature, curve_alpha, ESTIMATOR_PROFILE["max_curvature_delta"]),
        _smooth_limited(_LAST_TRACK.lookahead_error, lookahead_error, alpha, ESTIMATOR_PROFILE["max_error_delta"]),
        confidence,
        False,
        red_environment,
    )
    _LAST_TRACK = track
    _LAST_TIMESTAMP = timestamp
    return track



# ---- policy.py ----

"""控制策略模块。

功能概述：根据赛道状态统一规划转向和速度。
输入输出：输入 `TrackState`、时间戳和 fastest/safe 模式，输出 `ControlCmd`。
处理流程：计算风险分量，选择驾驶状态，生成目标转向和速度，再做平滑与变化率限制。
"""



_LAST_STEERING = 0.0
_LAST_SPEED = 0.0
_LAST_TIMESTAMP = None
_LOST_FRAMES = 0
_RECOVERY_FRAMES = 0
_LAST_GOOD_BIAS = 0.0
_LAST_MODE = "start"
_STALL_FRAMES = 0
_ESCAPE_FRAMES = 0
_ESCAPE_STEERING_SIGN = 1.0
_ESCAPE_STEERING_MAGNITUDE = 0.0
_ESCAPE_SPEED = 0.0
_LAST_TRACK_SIGNATURE = None
_STRAIGHT_MEMORY_FRAMES = 0


def reset_policy_state() -> None:
    """重置策略跨帧状态。

    功能：清空上一帧转向、速度、时间戳和恢复计数。
    参数：无。
    返回：无。
    逻辑：测试或新仿真开始前调用，避免继承旧平滑状态。
    """

    global _LAST_STEERING, _LAST_SPEED, _LAST_TIMESTAMP
    global _LOST_FRAMES, _RECOVERY_FRAMES, _LAST_GOOD_BIAS, _LAST_MODE
    global _STALL_FRAMES, _ESCAPE_FRAMES, _ESCAPE_STEERING_SIGN, _ESCAPE_STEERING_MAGNITUDE, _ESCAPE_SPEED
    global _LAST_TRACK_SIGNATURE, _STRAIGHT_MEMORY_FRAMES
    _LAST_STEERING = 0.0
    _LAST_SPEED = 0.0
    _LAST_TIMESTAMP = None
    _LOST_FRAMES = 0
    _RECOVERY_FRAMES = 0
    _LAST_GOOD_BIAS = 0.0
    _LAST_MODE = "start"
    _STALL_FRAMES = 0
    _ESCAPE_FRAMES = 0
    _ESCAPE_STEERING_SIGN = 1.0
    _ESCAPE_STEERING_MAGNITUDE = 0.0
    _ESCAPE_SPEED = 0.0
    _LAST_TRACK_SIGNATURE = None
    _STRAIGHT_MEMORY_FRAMES = 0


def _maybe_reset_policy_by_timestamp(timestamp: float, profile: dict) -> None:
    """根据时间戳判断是否重置策略状态。"""

    if _LAST_TIMESTAMP is None:
        return
    elapsed = float(timestamp) - float(_LAST_TIMESTAMP)
    if elapsed < 0.0 or elapsed > profile["timestamp_reset_gap"]:
        reset_policy_state()


def _dt(timestamp: float, profile: dict) -> float:
    """计算本帧控制间隔，首帧使用 nominal_dt。"""

    if _LAST_TIMESTAMP is None:
        return profile["nominal_dt"]
    return max(float(timestamp) - float(_LAST_TIMESTAMP), profile["nominal_dt"])


def _signed_power(value: float, power: float) -> float:
    """保留符号的幂函数。"""

    return math.copysign(abs(value) ** power, value)


def _road_direction_sign(track: TrackState) -> float:
    """估计应朝哪一侧打轮才能回到路面（左负右正）。

    功能：为脱困提供"路在哪边"的方向，而不是写死方向或盲目反打上一帧。
    参数：`track` 是当前赛道状态。
    返回：`+1.0`（向右回到路面）或 `-1.0`（向左回到路面）。
    逻辑：优先用当前横向误差；贴墙丢线时退回最近一次可信偏置；都不可用时反打上一帧舵角脱离。
    """

    reference = track.lateral_error
    if abs(reference) <= 0.05:
        reference = _LAST_GOOD_BIAS
    if abs(reference) <= 1e-3:
        reference = -_LAST_STEERING
    if abs(reference) <= 1e-6:
        return 1.0
    return math.copysign(1.0, reference)


def _control_signals(track: TrackState, profile: dict) -> dict:
    """计算策略使用的风险分量。

    功能：拆分弯道、偏移、置信度和丢线风险。
    参数：`track` 是赛道状态，`profile` 是控制参数。
    返回：包含各类风险和综合风险的字典。
    逻辑：速度和模式选择共享这些风险，避免重复估算。
    """

    curve_risk = clamp(max(abs(track.curvature), abs(track.heading_error), abs(track.lookahead_error)), 0.0, 1.0)
    offset_risk = clamp(abs(track.lateral_error), 0.0, 1.0)
    confidence_risk = clamp(1.0 - track.confidence, 0.0, 1.0)
    lost_risk = 1.0 if track.lost else 0.0
    turn_demand = clamp(curve_risk * 0.55 + offset_risk * 0.45, 0.0, 1.0)
    risk = clamp(
        curve_risk * profile["risk_curve_weight"]
        + offset_risk * profile["risk_offset_weight"]
        + confidence_risk * profile["risk_confidence_weight"]
        + lost_risk * profile["risk_lost_weight"],
        0.0,
        1.0,
    )
    return {
        "curve_risk": curve_risk,
        "offset_risk": offset_risk,
        "confidence_risk": confidence_risk,
        "lost_risk": lost_risk,
        "turn_demand": turn_demand,
        "risk": risk,
    }


def _is_straight_candidate(track: TrackState, signals: dict, profile: dict) -> bool:
    """判断当前几何是否足够像直道。

    功能：给直道提速和 lost 惯性滑行提供稳定判据。
    参数：`track` 是赛道状态，`signals` 是风险分量，`profile` 是控制参数。
    返回：当前非丢线帧是否可以视为直道。
    逻辑：主要看曲率、前瞻和横向偏移；heading 只做宽松兜底，避免噪声把直道判坏。
    """

    if track.lost or track.confidence < profile["lost_confidence"]:
        return False
    stable_curve = max(abs(track.curvature), abs(track.lookahead_error)) <= profile["straight_curve_max"]
    centered = signals["offset_risk"] <= profile["straight_offset_max"]
    heading_ok = abs(track.heading_error) <= profile["straight_heading_max"]
    return stable_curve and centered and heading_ok


def _is_lost_straight_coast_candidate(track: TrackState, signals: dict, profile: dict) -> bool:
    """判断丢线帧是否仍可按直道惯性滑行。

    功能：处理蓝门/天空造成的无观测帧，避免直道速度掉回 0.24。
    参数：`track` 是已衰减的丢线状态，`signals` 是风险分量，`profile` 是控制参数。
    返回：当前 lost 帧是否可安全维持直道速度。
    逻辑：只接受居中、曲率/前瞻低、heading 不大且上一帧舵角很小的 lost 帧。
    """

    if not track.lost:
        return False
    stable_curve = max(abs(track.curvature), abs(track.lookahead_error)) <= profile["straight_curve_max"]
    centered = signals["offset_risk"] <= profile["straight_offset_max"]
    heading_ok = abs(track.heading_error) <= profile["straight_heading_max"]
    steering_ok = abs(_LAST_STEERING) <= profile["straight_lost_steering_max"]
    return stable_curve and centered and heading_ok and steering_ok


def _update_straight_memory(track: TrackState, signals: dict, mode: str, profile: dict) -> bool:
    """更新直道记忆并返回本帧是否允许直道滑行。

    功能：让蓝门/天空造成的短暂 lost 不再立刻砸到 `lost_speed`。
    参数：当前赛道状态、风险信号、驾驶状态和参数表。
    返回：是否仍处在最近确认过的直道窗口内。
    逻辑：非 lost 直道帧刷新记忆；lost 帧可消耗记忆，或在几何和上一帧舵角都很直时直接滑行。
    """

    global _STRAIGHT_MEMORY_FRAMES

    if _is_straight_candidate(track, signals, profile):
        _STRAIGHT_MEMORY_FRAMES = int(profile["straight_memory_frames"])
        return True
    if _STRAIGHT_MEMORY_FRAMES > 0 and mode == "lost":
        _STRAIGHT_MEMORY_FRAMES -= 1
        return True
    if _is_lost_straight_coast_candidate(track, signals, profile):
        return True
    _STRAIGHT_MEMORY_FRAMES = 0
    return False


def _select_mode(track: TrackState, signals: dict, timestamp: float, profile: dict) -> str:
    """选择内部驾驶状态。

    功能：在 lost、recovering、hard_turn、correcting、cruise 之间切换。
    参数：`track` 是赛道状态，`signals` 是风险分量，`timestamp` 是平台时间。
    返回：内部状态名。
    逻辑：丢线优先，其次恢复缓冲、急弯、回中和巡航。
    """

    del timestamp
    if track.lost or track.confidence < profile["lost_confidence"]:
        return "lost"
    if _RECOVERY_FRAMES > 0 or track.confidence < profile["recovery_confidence"]:
        return "recovering"
    if (
        signals["curve_risk"] > profile["hard_turn_threshold"]
        or signals["turn_demand"] > profile["hard_turn_threshold"]
    ):
        return "hard_turn"
    if abs(track.lateral_error) > profile["correction_error"]:
        return "correcting"
    return "cruise"


def _target_steering(track: TrackState, signals: dict, mode: str, profile: dict) -> float:
    """计算目标转向。

    功能：把回中项和前瞻项分开组合，并按状态修正。
    参数：`track` 是赛道状态，`signals` 是风险分量，`mode` 是内部驾驶状态。
    返回：裁剪到 `[-1, 1]` 的目标转向。
    逻辑：偏移大时更看近处，弯道明显时更看前方；两者冲突时优先回中。
    """

    center_term = track.lateral_error * profile["gain_lateral"]
    lookahead_term = (
        track.lookahead_error * profile["gain_lookahead"]
        + track.heading_error * profile["gain_heading"]
        + track.curvature * profile["gain_curve"]
    )
    # 入弯时机门控：直道上车还居中、近处还直时（lateral/heading≈0），远处的路已弯会让前瞻项
    # 提前打轮→切内线贴栏杆。用近处弯量衡量"弯到了没"，弯没到就压制前瞻项，弯真正到了再放开，
    # 让车跟着中心线、到弯了再转。带保守下限，避免压过头变成转太晚冲外侧。
    corner_arrival = clamp(
        abs(track.lateral_error) / profile["turn_in_lateral_ref"]
        + abs(track.heading_error) / profile["turn_in_heading_ref"],
        0.0,
        1.0,
    )
    turn_in_gate = profile["turn_in_floor"] + (1.0 - profile["turn_in_floor"]) * corner_arrival
    lookahead_term *= turn_in_gate
    near_weight = profile["near_weight_base"] + signals["offset_risk"] * profile["near_weight_offset_boost"]
    far_weight = profile["far_weight_base"] + signals["curve_risk"] * profile["far_weight_curve_boost"]
    if center_term * lookahead_term < 0.0:
        conflict_offset = max(0.0, signals["offset_risk"] - profile["far_conflict_offset_start"])
        far_weight *= max(
            profile["far_conflict_min_scale"],
            1.0 - conflict_offset * profile["far_conflict_offset_scale"],
        )

    raw = near_weight * center_term + far_weight * lookahead_term
    raw += profile["gain_lateral_nonlinear"] * _signed_power(track.lateral_error, 1.7)
    raw += profile["gain_curve_nonlinear"] * _signed_power(track.curvature, 1.5)

    if mode == "lost":
        # 不再死保上一帧舵角（贴墙时那正是把车怼进墙的舵），向最近可信道路方向
        # 偏置靠拢并整体衰减，让车松开栏杆等感知恢复，真正的反向由脱困状态机负责。
        raw = 0.50 * _LAST_STEERING + 0.20 * _LAST_GOOD_BIAS
    elif mode == "recovering":
        raw *= 0.70
    elif mode == "correcting":
        raw += track.lateral_error * 0.25
    elif mode == "hard_turn":
        raw *= profile["hard_turn_steering_scale"]

    if (
        track.red_environment
        and
        track.lateral_error > profile["inside_left_lateral_min"]
        and track.heading_error < profile["inside_left_heading_max"]
        and track.curvature < profile["inside_left_curvature_max"]
    ):
        raw = max(raw, profile["inside_left_steering_limit"])

    if abs(raw) < profile["steering_deadzone"]:
        raw = 0.0
    max_abs = profile["max_abs_steering"]
    return clamp(raw, -max_abs, max_abs)


def _steering_smoothing_for_mode(mode: str, profile: dict) -> float:
    """读取当前驾驶状态对应的转向平滑系数。"""

    if mode == "cruise":
        return profile["steering_smoothing_cruise"]
    if mode == "hard_turn":
        return profile["steering_smoothing_turn"]
    if mode == "correcting":
        return profile["steering_smoothing_correction"]
    return profile["steering_smoothing_recovery"]


def _smooth_steering(target: float, mode: str, timestamp: float, profile: dict) -> float:
    """平滑转向并限制变化率。

    功能：按驾驶状态和速度限制方向盘跳变。
    参数：`target` 是目标转向，`mode` 是内部状态，`timestamp` 是平台时间。
    返回：平滑后的转向值。
    逻辑：高速时限制更强，恢复状态更平滑。
    """

    alpha = _steering_smoothing_for_mode(mode, profile)
    smoothed = _LAST_STEERING * alpha + target * (1.0 - alpha)
    dt_factor = max(1.0, _dt(timestamp, profile) / profile["nominal_dt"])
    speed_norm = clamp(_LAST_SPEED / max(profile["max_speed"], 1e-6), 0.0, 1.0)
    speed_factor = 1.0 - 0.35 * speed_norm
    max_delta = profile["max_steering_delta"] * dt_factor * speed_factor
    delta = clamp(smoothed - _LAST_STEERING, -max_delta, max_delta)
    # 速度相关的转向幅值上限：高速时收舵，避免同样舵角在高速下半径过小切内线。
    max_abs = profile["max_abs_steering"] * (1.0 - profile["steering_speed_cap_scale"] * speed_norm)
    return clamp(_LAST_STEERING + delta, -max_abs, max_abs)


def _target_speed(
    track: TrackState,
    signals: dict,
    mode: str,
    steering: float,
    timestamp: float,
    profile: dict,
    straight_memory_active: bool = False,
) -> float:
    """计算目标速度。

    功能：用乘法降速组合弯道、偏移、置信度和转向风险。
    参数：`track` 是赛道状态，`signals` 是风险分量，`mode` 是内部状态，`steering` 是当前转向；
        `straight_memory_active` 表示最近刚确认过直道。
    返回：目标速度比例。
    逻辑：模式只限制速度上限，正常速度由风险因子相乘得到。
    """

    if mode == "lost":
        if straight_memory_active:
            return profile["straight_lost_speed"]
        return profile["lost_speed"]

    curve_factor = 1.0 - profile["curve_slowdown"] * (signals["curve_risk"] ** profile["curve_power"])
    offset_factor = 1.0 - profile["offset_slowdown"] * (signals["offset_risk"] ** profile["offset_power"])
    confidence_factor = profile["min_confidence_factor"] + (1.0 - profile["min_confidence_factor"]) * track.confidence
    steering_factor = 1.0 - profile["steering_slowdown"] * (abs(steering) ** profile["steering_power"])
    target = profile["base_speed"] * curve_factor * offset_factor * confidence_factor * steering_factor

    if mode == "recovering":
        target = min(target, profile["recovery_speed"])
    elif mode == "hard_turn":
        centered_bonus = (
            profile["hard_turn_center_speed_bonus"]
            * (1.0 - signals["offset_risk"])
            * track.confidence
        )
        target = min(target, profile["hard_turn_speed"] + centered_bonus)
    elif mode == "correcting":
        target = min(target, profile["correction_speed"])
    # 直道提速：几何明确为直时，速度不该被偏低的 mask 置信度或 recovering 限速压住。
    # 判断主要看 curvature/lookahead/offset，heading 只做宽松兜底，避免噪声挡住直道加速。
    straight = straight_memory_active or _is_straight_candidate(track, signals, profile)
    if straight:
        target = max(target, profile["straight_speed"])
    if timestamp < profile["start_caution_seconds"]:
        target = min(target, profile["start_speed"])
    return clamp(target, profile["min_speed"], profile["max_speed"])


def _smooth_speed(target: float, timestamp: float, profile: dict) -> float:
    """平滑速度并限制加减速。

    功能：让加速慢、减速快，减少速度跳变。
    参数：`target` 是目标速度，`timestamp` 是平台时间，`profile` 是控制参数。
    返回：平滑后的速度比例。
    逻辑：上升和下降使用不同变化率，入弯能更快降速。
    """

    dt = _dt(timestamp, profile)
    delta = target - _LAST_SPEED
    if delta >= 0.0:
        delta = min(delta, profile["max_speed_increase_per_sec"] * dt)
    else:
        delta = max(delta, -profile["max_speed_decrease_per_sec"] * dt)
    return clamp(_LAST_SPEED + delta, min(profile["min_speed"], target), profile["max_speed"])


def _track_signature(track: TrackState) -> tuple[float, float, float, float, float]:
    """提取用于判断画面是否停滞的几何签名。"""

    return (
        track.lateral_error,
        track.heading_error,
        track.curvature,
        track.lookahead_error,
        track.confidence,
    )


def _escape_if_stalled(
    track: TrackState,
    signals: dict,
    steering: float,
    speed: float,
    mode: str,
    profile: dict,
    allow_geometry_escape: bool,
) -> tuple[float, float, str]:
    """在顶住边界时短暂脱困。

    功能：检测急弯大转向卡边，或长时间低速且几何签名几乎不变的状态。
    参数：当前赛道状态、风险信号、已平滑的转向和速度、内部模式、参数表，
        `allow_geometry_escape` 控制是否启用依赖可靠几何的急弯/大偏移脱困（仅 complex）。
    返回：可能被覆盖后的 `(steering, speed, mode)`。
    逻辑：脱困方向统一朝感知到的路面一侧（远离顶住的栏杆），不再写死方向或盲目反打；
        低速贴墙本就是低置信状态，所以低速脱困放宽置信度门槛，basic 也启用。
    """

    global _STALL_FRAMES, _ESCAPE_FRAMES, _ESCAPE_STEERING_SIGN, _ESCAPE_STEERING_MAGNITUDE, _ESCAPE_SPEED
    global _LAST_TRACK_SIGNATURE

    signature = _track_signature(track)
    if _LAST_TRACK_SIGNATURE is None:
        signature_delta = 1.0
    else:
        signature_delta = sum(abs(a - b) for a, b in zip(signature, _LAST_TRACK_SIGNATURE))
    _LAST_TRACK_SIGNATURE = signature

    if _ESCAPE_FRAMES > 0:
        _ESCAPE_FRAMES -= 1
        escape_steering = _ESCAPE_STEERING_SIGN * _ESCAPE_STEERING_MAGNITUDE
        max_abs = profile["max_abs_steering"]
        return (
            clamp(escape_steering, -max_abs, max_abs),
            max(speed, _ESCAPE_SPEED),
            "escaping",
        )

    high_turn = (
        signals["curve_risk"] >= profile["escape_curve_threshold"]
        or abs(steering) >= profile["escape_steering_threshold"]
    )
    aligned_offset = (
        signals["offset_risk"] >= profile["escape_offset_threshold"]
        and track.lateral_error * track.lookahead_error >= profile["escape_offset_lookahead_alignment"]
    )
    large_offset_stall = (
        allow_geometry_escape
        and mode in {"hard_turn", "correcting"}
        and signals["offset_risk"] >= profile["escape_offset_threshold"]
        and speed <= profile["escape_offset_speed_threshold"]
        and abs(track.heading_error) <= profile["escape_offset_heading_abs_max"]
        and abs(track.curvature) <= profile["escape_offset_curve_abs_max"]
        and track.lateral_error * track.lookahead_error >= profile["escape_offset_lookahead_alignment"]
    )
    low_speed_stall = speed <= profile["escape_low_speed_threshold"]
    # 顶住栏杆但速度还没塌到低速阈值（落在 low_speed 覆盖空档）：几何冻结 + 大偏移 + 大反向打轮。
    pinned_stall = (
        abs(track.lateral_error) >= profile["escape_pinned_lateral_min"]
        and abs(steering) >= profile["escape_pinned_steering_min"]
        and speed <= profile["escape_pinned_speed_max"]
    )
    stable_view = signature_delta <= profile["escape_signature_delta"]

    # 统一脱困方向：朝感知到的路面一侧打，远离顶住的栏杆。
    escape_sign = _road_direction_sign(track)

    should_count_stall = False
    require_confidence = True
    trigger_frames = int(profile["escape_trigger_frames"])
    escape_frames = int(profile["escape_turn_frames"])
    escape_steering = profile["escape_turn_steering"]
    escape_speed = profile["escape_turn_speed"]
    if large_offset_stall:
        should_count_stall = True
        trigger_frames = int(profile["escape_offset_trigger_frames"])
        escape_frames = int(profile["escape_offset_frames"])
        escape_steering = profile["escape_offset_steering"]
        escape_speed = profile["escape_offset_speed"]
    elif allow_geometry_escape and mode == "hard_turn" and high_turn and not aligned_offset:
        should_count_stall = True
    elif pinned_stall:
        # basic/complex 都启用：几何冻结地顶住栏杆、speed 又没低到触发 low_speed 时的兜底。
        should_count_stall = True
        trigger_frames = int(profile["escape_pinned_trigger_frames"])
        escape_frames = int(profile["escape_pinned_frames"])
        escape_steering = profile["escape_pinned_steering"]
        escape_speed = profile["escape_pinned_speed"]
    elif low_speed_stall:
        should_count_stall = True
        # 贴墙被卡本就是低置信/丢线状态，放宽门槛，否则脱困永远进不来。
        require_confidence = False
        trigger_frames = int(profile["escape_low_speed_trigger_frames"])
        escape_frames = int(profile["escape_low_speed_frames"])
        escape_steering = profile["escape_low_speed_steering"]
        escape_speed = profile["escape_low_speed_speed"]

    confidence_ok = (not require_confidence) or (
        not track.lost and track.confidence >= profile["escape_min_confidence"]
    )
    if should_count_stall and stable_view and confidence_ok:
        _STALL_FRAMES += 1
    else:
        _STALL_FRAMES = 0

    if _STALL_FRAMES >= trigger_frames:
        _STALL_FRAMES = 0
        _ESCAPE_STEERING_SIGN = escape_sign
        _ESCAPE_STEERING_MAGNITUDE = escape_steering
        _ESCAPE_SPEED = escape_speed
        _ESCAPE_FRAMES = escape_frames

    return steering, speed, mode


def _update_policy_state(track: TrackState, steering: float, speed: float, mode: str, timestamp: float, profile: dict) -> None:
    """写回策略跨帧状态。

    功能：维护丢线计数、恢复缓冲、最近可信方向和上一帧控制量。
    参数：`track` 是赛道状态，`steering` 和 `speed` 是本帧输出。
    返回：无。
    逻辑：刚从丢线恢复时保守若干帧；高置信时更新恢复方向偏置。
    """

    global _LAST_STEERING, _LAST_SPEED, _LAST_TIMESTAMP
    global _LOST_FRAMES, _RECOVERY_FRAMES, _LAST_GOOD_BIAS, _LAST_MODE

    if track.lost:
        _LOST_FRAMES += 1
    else:
        if _LOST_FRAMES > 0:
            _RECOVERY_FRAMES = int(profile["recovery_frames"])
        _LOST_FRAMES = 0
    if _RECOVERY_FRAMES > 0 and not track.lost:
        _RECOVERY_FRAMES -= 1

    if not track.lost and track.confidence >= profile["recovery_confidence"]:
        _LAST_GOOD_BIAS = clamp(
            track.lateral_error * 0.55 + track.lookahead_error * 0.25 + track.curvature * 0.20,
            -1.0,
            1.0,
        )

    _LAST_STEERING = steering
    _LAST_SPEED = speed
    _LAST_TIMESTAMP = timestamp
    _LAST_MODE = mode


def decide_control(track: TrackState, timestamp: float, mode: str = "fastest") -> ControlCmd:
    """计算最终控制命令。

    功能：按 fastest 或 safe 参数统一生成转向和速度。
    参数：`track` 是赛道状态，`timestamp` 是平台时间，`mode` 是参数模式。
    返回：`ControlCmd`，包含 `steering` 和 `speed`。
    逻辑：非法模式回退 fastest；内部用状态机协同转向、速度和恢复策略。
    """

    profile = get_profile(mode if mode in {"fastest", "safe"} else "fastest")
    if not track.red_environment:
        profile.update(BASIC_CONTROL_OVERRIDES)
    timestamp = float(timestamp)
    _maybe_reset_policy_by_timestamp(timestamp, profile)
    signals = _control_signals(track, profile)
    drive_mode = _select_mode(track, signals, timestamp, profile)
    straight_memory_active = _update_straight_memory(track, signals, drive_mode, profile)
    target_steering = _target_steering(track, signals, drive_mode, profile)
    steering = _smooth_steering(target_steering, drive_mode, timestamp, profile)
    target_speed = _target_speed(
        track,
        signals,
        drive_mode,
        steering,
        timestamp,
        profile,
        straight_memory_active=straight_memory_active,
    )
    speed = _smooth_speed(target_speed, timestamp, profile)
    # 低速贴墙脱困两条赛道都启用；依赖可靠几何的急弯/大偏移脱困仍只在 complex(red)。
    steering, speed, drive_mode = _escape_if_stalled(
        track, signals, steering, speed, drive_mode, profile, track.red_environment
    )
    _update_policy_state(track, steering, speed, drive_mode, timestamp, profile)
    return ControlCmd(steering, speed)



# ---- team_controller_local.py ----

"""本地控制器入口。

功能概述：按固定流水线串接感知、估计和控制策略模块。
输入输出：输入平台同形态的左右图像和时间戳，输出 `(steering, speed)`。
处理流程：提取观测，估计赛道，按 profile 决策控制量，最后限幅返回。
"""



PROFILE = "fastest"


def _segments_from_active(active: np.ndarray) -> list[tuple[int, int]]:
    if active.size == 0:
        return []
    padded = np.concatenate(([False], active.astype(bool), [False]))
    changes = np.flatnonzero(padded[1:] != padded[:-1])
    return [(int(changes[i]), int(changes[i + 1] - 1)) for i in range(0, len(changes), 2)]


def _camera_line_state(image: np.ndarray, profile: dict) -> tuple[float, float, float] | None:
    """估计单个相机里的白色中心线。

    功能：找连续的窄白色虚线，输出近处偏移、线方向和置信度。
    参数：`image` 是 BGR 图像，`profile` 是白线跟踪参数。
    返回：`(offset, heading, confidence)`；白线不足时返回 None。
    逻辑：逐行找短白段并按连续性串起来，排除车身大白块和孤立噪声。
    """

    if image is None or not hasattr(image, "shape") or len(image.shape) != 3:
        return None
    height, width = image.shape[:2]
    lower = int(profile["white_min"])
    mask = cv2.inRange(image, (lower, lower, lower), (255, 255, 255))
    kernel = np.ones((3, 3), dtype=np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel, iterations=1)

    rows = np.linspace(
        int(height * profile["scan_bottom_ratio"]),
        int(height * profile["scan_top_ratio"]),
        int(profile["scan_count"]),
        dtype=np.int32,
    )
    row_band = int(profile["row_band"])
    min_width = float(profile["min_segment_width"])
    max_width = float(profile["max_segment_width"])
    initial_limit = float(width) * profile["initial_center_max_offset"]
    jump_limit = float(width) * profile["max_center_jump_ratio"]
    image_center = float(width) * 0.5

    points = []
    previous_center = image_center
    has_previous = False
    for y in rows:
        y0 = max(int(y) - row_band, 0)
        y1 = min(int(y) + row_band + 1, height)
        band = mask[y0:y1, :]
        active = np.count_nonzero(band, axis=0) >= 2
        candidates = []
        for left, right in _segments_from_active(active):
            segment_width = float(right - left + 1)
            if not (min_width <= segment_width <= max_width):
                continue
            center = (float(left) + float(right)) * 0.5
            if not has_previous and abs(center - image_center) <= initial_limit:
                candidates.append(center)
            elif has_previous and abs(center - previous_center) <= jump_limit:
                candidates.append(center)
        if not candidates:
            continue
        center = min(candidates, key=lambda value: abs(value - previous_center))
        points.append((center, float(y)))
        previous_center = center
        has_previous = True

    min_points = int(profile["min_points_per_camera"])
    if len(points) < min_points:
        return None
    point_arr = np.array(points, dtype=np.float32)
    y = point_arr[:, 1]
    x = point_arr[:, 0]
    y_span = float(np.max(y) - np.min(y))
    if y_span < float(profile["min_y_span"]):
        return None
    coeffs = np.polyfit(y, x, deg=1)
    near_x = float(np.polyval(coeffs, height * profile["near_y_ratio"]))
    far_x = float(np.polyval(coeffs, height * profile["far_y_ratio"]))
    offset = (near_x - image_center) / max(image_center, 1.0)
    heading = (far_x - near_x) / max(image_center, 1.0)
    confidence = clamp(len(points) / float(profile["scan_count"]), 0.0, 1.0)
    return clamp(offset, -1.0, 1.0), clamp(heading, -1.0, 1.0), confidence


def _lane_line_correction(left_img, right_img, profile: dict) -> tuple[float, float] | None:
    """融合左右相机白线误差。

    功能：估计白线相对车身中轴的位置和方向。
    参数：左右 BGR 图像和白线参数。
    返回：`(correction, confidence)`；不可信时返回 None。
    逻辑：左右相机都看到连续白线时才强校正，避免单目被车身、栏杆或断线误导。
    """

    if not profile["enable"]:
        return None
    left = _camera_line_state(left_img, profile)
    right = _camera_line_state(right_img, profile)
    if left is None or right is None:
        return None
    offset = (left[0] + right[0]) * 0.5
    heading = (left[1] + right[1]) * 0.5
    confidence = min(left[2], right[2])
    if confidence < profile["min_confidence"]:
        return None
    correction = offset * profile["offset_gain"] + heading * profile["heading_gain"]
    correction = clamp(correction, -profile["max_correction"], profile["max_correction"])
    return correction, confidence


def _apply_lane_line_correction(cmd: ControlCmd, left_img, right_img) -> ControlCmd:
    """用白线误差小幅修正舵角。

    功能：让车身中线追向白色虚线，同时保持原道路中心控制作为兜底。
    参数：原始控制命令和左右相机图像。
    返回：修正后的控制命令。
    逻辑：白线可信时只加有限幅度的舵角修正，不直接覆盖速度和状态机。
    """

    line = _lane_line_correction(left_img, right_img, LINE_FOLLOW_PROFILE)
    if line is None:
        return cmd
    correction, _confidence = line
    return ControlCmd(clamp(cmd.steering + correction, -1.0, 1.0), cmd.speed)


def control(left_img, right_img, timestamp):
    """平台兼容的控制入口。

    功能：提供 `control(left_img, right_img, timestamp)` 接口。
    参数：`left_img`、`right_img` 是 BGR 图像，`timestamp` 是仿真时间。
    返回：`(steering, speed)`，两个值都在平台允许范围内。
    逻辑：仅负责模块接线和异常兜底，具体算法留在各职责模块中。
    """

    try:
        obs = extract_observation(left_img, right_img, timestamp)
        track = estimate_track(obs, timestamp)
        cmd = decide_control(track, timestamp, mode=PROFILE)
        cmd = _apply_lane_line_correction(cmd, left_img, right_img)
        steering, speed = clamp_cmd(cmd)
        return steering, speed
    except Exception:
        return 0.0, 0.0
