"""提交文件构建脚本。

功能概述：把 `controller/` 的模块化代码合并成单个 `team_controller.py`。
输入输出：读取本地控制器源码，输出平台可上传的自包含文件。
处理流程：按固定顺序拼接模块，删除本地 import，把 `PROFILE` 固定为命令传入的模式。
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTROLLER_DIR = ROOT / "controller"
DEFAULT_OUTPUTS = {
    "fastest": ROOT / "submissions" / "fastest" / "team_controller.py",
    "safe": ROOT / "submissions" / "safe" / "team_controller.py",
}
MODULE_ORDER = [
    "common.py",
    "params.py",
    "perception.py",
    "estimator.py",
    "strategy.py",
    "steering.py",
    "team_controller_local.py",
]


def strip_local_imports(source: str) -> str:
    """移除提交文件不应保留的本地 import。

    功能：让生成文件不依赖 `controller/` 包。
    参数：`source` 是单个模块源码。
    返回：删除本地 import 行后的源码。
    逻辑：外部允许库由构建头部统一导入，模块间依赖由拼接顺序解决。
    """

    kept_lines = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("from __future__"):
            continue
        if stripped.startswith("from controller.") or stripped.startswith("from ."):
            continue
        if stripped in {
            "import cv2",
            "import math",
            "import numpy as np",
            "from dataclasses import dataclass",
        }:
            continue
        kept_lines.append(line)
    return "\n".join(kept_lines).strip()


def read_module(name: str, mode: str) -> str:
    """读取并清理控制器模块。

    功能：按文件名读取 `controller/` 下的模块源码。
    参数：`name` 是模块文件名，`mode` 是构建策略。
    返回：可拼接到提交文件中的源码片段。
    逻辑：读取文本后移除本地 import；入口模块里把 PROFILE 替换为固定模式。
    """

    source = (CONTROLLER_DIR / name).read_text(encoding="utf-8")
    source = strip_local_imports(source)
    if name == "team_controller_local.py":
        source = source.replace('PROFILE = "fastest"', f'PROFILE = "{mode}"')
        source = source.replace('PROFILE = "safe"', f'PROFILE = "{mode}"')
    return source


def build_source(mode: str) -> str:
    """构建单文件控制器源码。

    功能：为指定模式生成自包含 Python 源码。
    参数：`mode` 为 `fastest` 或 `safe`。
    返回：完整源码字符串。
    逻辑：写入允许 import，再按契约顺序拼接所有控制器模块。
    """

    parts = [
        "# Generated by scripts/build_submission.py. Edit controller/ instead.\n"
        "from dataclasses import dataclass\n"
        "import math\n\n"
        "import cv2\n"
        "import numpy as np\n"
    ]
    for module in MODULE_ORDER:
        parts.append(f"\n# ---- {module} ----\n")
        parts.append(read_module(module, mode))
        parts.append("\n")
    return "\n".join(parts).strip() + "\n"


def parse_args():
    """解析命令行参数。

    功能：读取构建模式和输出路径。
    参数：无。
    返回：`argparse.Namespace`。
    逻辑：模式只允许 fastest 和 safe，未指定输出时写入对应 submissions 目录。
    """

    parser = argparse.ArgumentParser(description="Build single-file AI Racer submission.")
    parser.add_argument("--mode", choices=sorted(DEFAULT_OUTPUTS), default="fastest")
    parser.add_argument("--out", type=Path, default=None)
    return parser.parse_args()


def main() -> int:
    """脚本入口。

    功能：生成指定模式的提交文件。
    参数：来自命令行。
    返回：进程退出码。
    逻辑：确定输出路径，创建父目录，写入源码并打印结果摘要。
    """

    args = parse_args()
    output = args.out or DEFAULT_OUTPUTS[args.mode]
    output = output if output.is_absolute() else ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_source(args.mode), encoding="utf-8")
    print(f"已生成 {args.mode}: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
